<?php

use yii\db\Migration;

/**
 * Class m180617_184144_country
 */
class m180617_184144_country extends Migration
{
    const TABLE = '{{%country}}';

    /**
     * @return bool|void
     * @throws \yii\db\Exception
     */
    public function safeUp()
    {
        $this->createTable(self::TABLE, [
            'country_id' => $this->primaryKey(3),
            'country_auto' => $this->integer(5)->defaultValue(0),
            'country_finance' => $this->integer(11)->defaultValue(0),
            'country_game' => $this->integer(5)->defaultValue(0),
            'country_name' => $this->string(255),
            'country_president_id' => $this->integer(11)->defaultValue(0),
            'country_president_vice_id' => $this->integer(11)->defaultValue(0),
            'country_stadium_capacity' => $this->integer(5)->defaultValue(0),
        ]);

        $this->insert(self::TABLE, [
            'country_name' => 'League'
        ]);

        $this->update(self::TABLE, ['country_id' => 0], ['country_id' => 1]);

        Yii::$app->db->createCommand('ALTER TABLE ' . self::TABLE . ' AUTO_INCREMENT=1')->execute();

        $this->batchInsert(self::TABLE, ['country_name'], [
            ['Afghanistan'],
            ['Albania'],
            ['Algeria'],
            ['Andorra'],
            ['Angola'],
            ['Antigua and Barbuda'],
            ['Argentina'],
            ['Armenia'],
            ['Australia'],
            ['Austria'],
            ['Azerbaijan'],
            ['Bahamas'],
            ['Bahrain'],
            ['Bangladesh'],
            ['Barbados'],
            ['Belarus'],
            ['Belgium'],
            ['Belize'],
            ['Benin'],
            ['Bolivia'],
            ['Bosnia and Herzegovina'],
            ['Botswana'],
            ['Brazil'],
            ['Brunei'],
            ['Bulgaria'],
            ['Burkina Faso'],
            ['Burundi'],
            ['Butane'],
            ['Cambodia'],
            ['Cameroon'],
            ['Canada'],
            ['Cape Verde'],
            ['CAR'],
            ['Chad'],
            ['Chile'],
            ['China'],
            ['Colombia'],
            ['Comoros'],
            ['Congo'],
            ['Costa Rica'],
            ["Côte d'Ivoire"],
            ['Croatia'],
            ['Cuba'],
            ['Cyprus'],
            ['Czech Republic'],
            ['Denmark'],
            ['Djibouti'],
            ['Dominica'],
            ['Dominican Republic'],
            ['DR Congo'],
            ['East Timor'],
            ['Ecuador'],
            ['Egypt'],
            ['England'],
            ['Equatorial Guinea'],
            ['Eritrea'],
            ['Estonia'],
            ['Ethiopia'],
            ['Fiji'],
            ['Finland'],
            ['France'],
            ['Gabon'],
            ['Gambia'],
            ['Georgia'],
            ['Germany'],
            ['Ghana'],
            ['Greece'],
            ['Grenada'],
            ['Guatemala'],
            ['Guinea'],
            ['Guinea-Bissau'],
            ['Guyana'],
            ['Haiti'],
            ['Honduras'],
            ['Hungary'],
            ['Iceland'],
            ['India'],
            ['Indonesia'],
            ['Iran'],
            ['Iraq'],
            ['Ireland'],
            ['Israel'],
            ['Italy'],
            ['Jamaica'],
            ['Japan'],
            ['Jordan'],
            ['Kazakhstan'],
            ['Kenya'],
            ['Kiribati'],
            ['Korea'],
            ['Kuwait'],
            ['Kyrgyzstan'],
            ['Laos'],
            ['Latvia'],
            ['Lebanon'],
            ['Lesotho'],
            ['Liberia'],
            ['Libya'],
            ['Liechtenstein'],
            ['Lithuania'],
            ['Luxembourg'],
            ['Macedonia'],
            ['Madagascar'],
            ['Malawi'],
            ['Malaysia'],
            ['Maldives'],
            ['Mali'],
            ['Malta'],
            ['Marshall Islands'],
            ['Mauritania'],
            ['Mauritius'],
            ['Mexico'],
            ['Micronesia'],
            ['Moldova'],
            ['Monaco'],
            ['Mongolia'],
            ['Montenegro'],
            ['Morocco'],
            ['Mozambique'],
            ['Myanmar'],
            ['Namibia'],
            ['Nauru'],
            ['Nepal'],
            ['Netherlands'],
            ['New Zealand'],
            ['North Korea'],
            ['Nicaragua'],
            ['Niger'],
            ['Nigeria'],
            ['Northern Ireland'],
            ['Norway'],
            ['Oman'],
            ['Pakistan'],
            ['Palau'],
            ['Panama'],
            ['Papua New Guinea'],
            ['Paraguay'],
            ['Peru'],
            ['Philippines'],
            ['Poland'],
            ['Portugal'],
            ['Qatar'],
            ['Romania'],
            ['Russia'],
            ['Rwanda'],
            ['Saint Kitts and Nevis'],
            ['Saint Lucia'],
            ['Saint Vincent and the Grenadines'],
            ['Salvador'],
            ['Samoa'],
            ['San marino'],
            ['Sao Tome and Principe'],
            ['Saudi Arabia'],
            ['Scotland'],
            ['Senegal'],
            ['Serbia'],
            ['Seychelles'],
            ['Sierra Leone'],
            ['Singapore'],
            ['Slovakia'],
            ['Slovenia'],
            ['Solomon islands'],
            ['Somalia'],
            ['South Africa'],
            ['South Sudan'],
            ['Spain'],
            ['Sri Lanka'],
            ['Sudan'],
            ['Suriname'],
            ['Swaziland'],
            ['Sweden'],
            ['Switzerland'],
            ['Syria'],
            ['Tajikistan'],
            ['Tanzania'],
            ['Thailand'],
            ['Togo'],
            ['Tonga'],
            ['Trinidad and Tobago'],
            ['Tunisia'],
            ['Turkey'],
            ['Turkmenistan'],
            ['Tuvalu'],
            ['Uganda'],
            ['Ukraine'],
            ['United Arab Emirates'],
            ['Uruguay'],
            ['USA'],
            ['Uzbekistan'],
            ['Vanuatu'],
            ['Venezuela'],
            ['Vietnam'],
            ['Wales'],
            ['Yemen'],
            ['Zambia'],
            ['Zimbabwe'],
        ]);
    }

    /**
     * @return bool|void
     */
    public function safeDown()
    {
        $this->dropTable(self::TABLE);
    }
}
