<?php

namespace console\models\start;

use common\components\ErrorHelper;
use common\models\Country;
use common\models\Name;
use common\models\NameCountry;
use Yii;
use yii\db\Exception;

/**
 * Class InsertName
 * @package console\models\start
 */
class InsertName
{
    /**
     * @throws Exception
     * @return void
     */
    public function execute(): void
    {
        $cheName = [
            'Jan',
            'Martin',
            'Petr',
            'Michal',
            'Tomas',
            'Filip',
            'David',
            'Daniel',
            'Jiri',
            'Jakub',
            'Pavel',
            'Lukas',
            'Ondrej',
            'Marek',
            'Milan',
            'Roman',
            'Zdenek',
            'Vojtech',
            'Jaroslav',
            'Dominik',
            'Miroslav',
            'Josef',
            'Vaclav',
            'Karel',
            'Stanislav',
            'Michael',
            'Richard',
            'Adam',
            'Patrik',
            'Ladislav',
            'Radek',
            'Honza',
            'Robert',
            'Frantisek',
            'Radim',
            'Matej',
            'Viktor',
            'Ales',
            'Stepan',
            'Denis',
            'Pista',
            'Vladimir',
            'Ivo',
            'Jirka',
            'Sebastian',
            'Erich',
            'Vit',
            'Nicolas',
            'Krystof',
            'Erik',
        ];
        $engName = [
            'Oliver',
            'Jack',
            'Harry',
            'Jacob',
            'Charlie',
            'Thomas',
            'Oscar',
            'William',
            'James',
            'George',
            'Alfie',
            'Joshua',
            'Noah',
            'Ethan',
            'Archie',
            'Leo',
            'Henry',
            'Joseph',
            'Samuel',
            'Riley',
            'Daniel',
            'Alexander',
            'Max',
            'Lucas',
            'Mason',
            'Logan',
            'Isaac',
            'Benjamin',
            'Dylan',
            'Jake',
            'Edward',
            'Finley',
            'Freddie',
            'Harrison',
            'Tyler',
            'Sebastian',
            'Zachary',
            'Adam',
            'Theo',
            'Jayden',
            'Arthur',
            'Toby',
            'Luke',
            'Lewis',
            'Matthew',
            'Harvey',
            'Harley',
            'David',
            'Ryan',
            'Tommy',
            'Michael',
            'Reuben',
            'Nathan',
            'Blake',
            'Jenson',
            'Bobby',
            'Luca',
            'Charles',
            'Frankie',
            'Dexter',
            'Kai',
            'Alex',
            'Connor',
            'Liam',
            'Jamie',
            'Elijah',
            'Stanley',
            'Louie',
            'Jude',
            'Callum',
            'Hugo',
            'Leon',
            'Elliot',
            'Louis',
            'Theodore',
            'Gabriel',
            'Ollie',
            'Aaron',
            'Frederick',
            'Evan',
            'Elliott',
            'Owen',
            'Teddy',
            'Finlay',
            'Caleb',
            'Ibrahim',
            'Ronnie',
            'Felix',
            'Aiden',
            'Cameron',
            'Austin',
            'Kian',
            'Rory',
            'Seth',
            'Robert',
            'Albert',
            'Sonny',
        ];
        $finName = [
            'Onni',
            'Elias',
            'Eetu',
            'Leo',
            'Aleksi',
            'Niilo',
            'Veeti',
            'Oliver',
            'Joona',
            'Eino',
            'Leevi',
            'Lauri',
            'Matias',
            'Mikael',
            'Lenni',
            'Rasmus',
            'Viljami',
            'Eemeli',
            'Väino',
            'Akseli',
            'Daniel',
            'Aatu',
            'Aapo',
            'Emil',
            'Julius',
            'Juho',
            'Valtteri',
            'Jimi',
            'Niklas',
            'Joel',
            'Vilho',
            'Otto',
            'Miro',
            'Eemil',
            'Eeli',
            'Anton',
            'Peetu',
            'Roope',
            'Arttu',
            'Toivo',
            'Kasper',
            'Oskari',
            'Nooa',
            'Konsta',
            'Jesse',
            'Eelis',
            'Samuel',
            'Samu',
            'Luukas',
            'Topias',
        ];
        $gerName = [
            'Alex',
            'Lukas',
            'Michael',
            'Daniel',
            'Philipp',
            'Jonas',
            'Fabian',
            'Marcel',
            'Tim',
            'Kevin',
            'Jan',
            'David',
            'Tom',
            'Markus',
            'Sebastian',
            'Julian',
            'Leon',
            'Christoph',
            'Simon',
            'Felix',
            'Andreas',
            'Nils',
            'Nico',
            'Martin',
            'Max',
            'Florian',
            'Dennis',
            'Patrick',
            'Thomas',
            'Christopher',
            'Moritz',
            'Nick',
            'Chris',
            'Paul',
            'Jonathan',
            'Tobias',
            'Jakob',
            'Christian',
            'Adrian',
            'Matthias',
            'Dominik',
            'Stefan',
            'Rene',
            'Marco',
            'Vincent',
            'Mohamed',
            'Kai',
            'Erik',
            'Ludwig',
            'Hendrik',
            'Mario',
            'Oliver',
            'Lucas',
            'Anton',
            'Timo',
            'Sven',
            'Marc',
            'Andre',
            'Gabriel',
            'Leo',
            'Arthur',
            'Maximilian',
            'Ben',
            'Jannik',
            'Niklas',
            'Noah',
            'Peter',
            'Mark',
            'Johannes',
            'Konrad',
            'Alexander',
            'Pierre',
            'Jason',
            'Frank',
            'Marvin',
            'Till',
            'Artur',
            'Luca',
            'Fabio',
            'Lasse',
            'Jens',
            'Konstantin',
            'Tamino',
            'William',
            'Luis',
            'Alihan',
            'Ricardo',
            'Victor',
            'Jeremy',
            'Brian',
            'Dustin',
            'Janis,Niels',
            'Jesse',
            'Phil',
            'Bako',
            'Gerrit',
        ];
        $norName = [
            'Alexander',
            'Andreas',
            'Arvid',
            'Bjorn',
            'Daniel',
            'Eirik',
            'Erling',
            'Frank',
            'Geir',
            'Harald',
            'Hakon',
            'Jan',
            'Johan',
            'Jon',
            'Jorgen',
            'Kenneth',
            'Kjetil',
            'Kristoffer',
            'Leif',
            'Marius',
            'Nils',
            'Ola',
            'Ove',
            'Pal',
            'Robert',
            'Roy',
            'Simen',
            'Steinar',
            'Svein',
            'Thomas',
            'Tommy',
            'Tore',
            'Vegard',
            'Alf',
            'Arild',
            'Asbjorn',
            'Christian',
            'Egil',
            'Eivind',
            'Espen',
            'Fredrik',
            'Gunnar',
            'Helge',
            'Havard',
            'Jarle',
            'Johannes',
            'Jonas',
            'Jorn',
            'Kim',
            'Knut',
            'Kare',
            'Magne',
            'Martin',
            'Odd',
            'Olav',
            'Per',
            'Reidar',
            'Roger',
            'Rune',
            'Sindre',
            'Stian',
            'Sverre',
            'Thor',
            'Tor',
            'Trond',
            'Vidar',
            'Anders',
            'Arne',
            'Bjarne',
            'Dag',
            'Einar',
            'Erik',
            'Finn',
            'Frode',
            'Hans',
            'Henrik',
            'Ivar',
            'Jens',
            'John',
            'Jostein',
            'Karl',
            'Kjell',
            'Kristian',
            'Lars',
            'Magnus',
            'Morten',
            'Oddvar',
            'Ole',
            'Petter',
            'Roar',
            'Rolf',
            'Sigurd',
            'Stein',
            'Stig',
            'Terje',
            'Tom',
            'Torbjorn',
            'Trygve',
            'Oystein',
            'Oyvind',
        ];
        $rusName = [
            'Aleksandr',
            'Maxim',
            'Artem',
            'Mikhail',
            'Daniil',
            'Ivan',
            'Dmitri',
            'Kirill',
            'Andrei',
            'Igor',
            'Ilya',
            'Timofei',
            'Alexei',
            'Matvei',
            'Nikita',
            'Vladimir',
            'Roman',
            'Mark',
            'Yaroslav',
            'Fyodor',
            'Sergei',
            'Lev',
            'Stepan',
            'Konstantin',
            'Vladislav',
            'Georgi',
            'Nikolai',
            'Gleb',
            'Timur',
            'Pavel',
        ];
        $sweName = [
            'Karl',
            'Erik',
            'Lars',
            'Anders',
            'Per',
            'Mikael',
            'Johan',
            'Olof',
            'Nils',
            'Jan',
            'Gustav',
            'Hans',
            'Lennart',
            'Peter',
            'Gunnar',
            'Sven',
            'Fredrik',
            'Thomas',
            'Bengt',
            'Bo',
            'Daniel',
            'Ake',
            'Goran',
            'Alexander',
            'Oskar',
            'Christer',
            'Andreas',
            'Stefan',
            'Magnus',
            'Martin',
            'Mats',
            'John',
            'Mattias',
            'Leif',
            'Henrik',
            'Ulf',
            'Bjorn',
            'Jonas',
            'Bertil',
            'Arne',
            'Axel',
            'Ingemar',
            'Robert',
            'Christian',
            'Marcus',
            'Niklas',
            'David',
            'Viktor',
            'Emil',
            'Kjell',
            'Mohamed',
            'Stig',
            'Hakan',
            'Patrik',
            'Rolf',
            'Rickard',
            'Christoffer',
            'Joakim',
            'Wilhelm',
            'Tommy',
            'Roland',
            'Filip',
            'William',
            'Claes',
            'Ingvar',
            'Simon',
            'Roger',
            'Sebastian',
            'Anton',
            'Kent',
            'Ove',
            'Johannes',
            'Tobias',
            'Kenneth',
            'Emanuel',
            'Jorgen',
            'Jonathan',
            'Jakob',
            'Kurt',
            'Hugo',
            'Robin',
            'Rune',
            'Elias',
            'Lucas',
            'Adam',
            'Gosta',
            'Georg',
            'Johnny',
            'Linus',
            'Sten',
            'Torbjorn',
            'Arvid',
            'Alf',
            'Dan',
            'Josef',
            'Oliver',
            'Borje',
            'Ali',
            'Albin',
            'Ludvig',
        ];

        $nameArray = [
            [
                'country' => 'Canada',
                'list' => $engName,
            ],
            [
                'country' => 'Russia',
                'list' => $rusName,
            ],
            [
                'country' => 'USA',
                'list' => $engName,
            ],
            [
                'country' => 'Finland',
                'list' => $finName,
            ],
            [
                'country' => 'Sweden',
                'list' => $sweName,
            ],
            [
                'country' => 'Czech Republic',
                'list' => $cheName,
            ],
            [
                'country' => 'Switzerland',
                'list' => $gerName,
            ],
            [
                'country' => 'Slovakia',
                'list' => $cheName,
            ],
            [
                'country' => 'Belarus',
                'list' => $rusName,
            ],
            [
                'country' => 'Germany',
                'list' => $gerName,
            ],
            [
                'country' => 'Norway',
                'list' => $norName,
            ],
            [
                'country' => 'Ukraine',
                'list' => $rusName,
            ],
        ];

        foreach ($nameArray as $country) {
            $countryId = Country::find()
                ->select(['country_id'])
                ->where(['country_name' => $country['country']])
                ->limit(1)
                ->scalar();

            foreach ($country['list'] as $item) {
                $transaction = Yii::$app->db->beginTransaction();
                try {
                    $name = Name::findOne(['name_name' => $item]);
                    if (!$name) {
                        $name = new Name();
                        $name->name_name = $item;
                        if (!$name->save()) {
                            throw new Exception(ErrorHelper::modelErrorsToString($name));
                        }
                    }

                    $nameCountry = new NameCountry();
                    $nameCountry->name_country_country_id = $countryId;
                    $nameCountry->name_country_name_id = $name->name_id;
                    if (!$nameCountry->save()) {
                        throw new Exception(ErrorHelper::modelErrorsToString($nameCountry));
                    }
                    $transaction->commit();
                } catch (Exception $e) {
                    $transaction->rollBack();
                    ErrorHelper::log($e);
                }
            }
        }
    }
}
