<?php

namespace console\models\start;

use common\components\ErrorHelper;
use common\models\City;
use common\models\Country;
use common\models\Stadium;
use common\models\Team;
use Yii;
use yii\db\Exception;

/**
 * Class InsertTeam
 * @package console\models\start
 */
class InsertTeam
{
    /**
     * @throws Exception
     * @return void
     */
    public function execute(): void
    {
        $team_array = [
//            [
//                'country' => 'Canada',
//                'list' => [
//                    ['team' => 'Abbotsford Heat', 'stadium' => 'Abbotsford', 'city' => 'Abbotsford'],
//                    ['team' => 'Brampton Beast', 'stadium' => '	Powerade', 'city' => 'Brampton'],
//                    ['team' => 'Vancouver Canucks', 'stadium' => 'Rogers', 'city' => 'Vancouver'],
//                    ['team' => 'Winnipeg Jets', 'stadium' => 'Bell MTS', 'city' => 'Winnipeg'],
//                    ['team' => 'Halifax Mooseheads', 'stadium' => 'Scotiabank', 'city' => 'Halifax'],
//                    ['team' => 'Hamilton Bulldogs', 'stadium' => 'FirstOntario', 'city' => 'Hamilton'],
//                    ['team' => 'Drummondville Voltigeurs', 'stadium' => 'Marcel Dionne', 'city' => 'Drummondville'],
//                    ['team' => 'Calgary Flames', 'stadium' => 'Scotiabank', 'city' => 'Calgary'],
//                    ['team' => 'Calgary Hitmen', 'stadium' => 'Scotiabank', 'city' => 'Calgary'],
//                    ['team' => 'Manitoba Moose', 'stadium' => 'Bell MTS', 'city' => 'Winnipeg'],
//                    ['team' => 'Montreal Canadiens', 'stadium' => 'Bell', 'city' => 'Montreal'],
//                    ['team' => 'Ottawa Senators', 'stadium' => 'Canadian Tire', 'city' => 'Ottawa'],
//                    ['team' => 'St. John\'s IceCaps', 'stadium' => 'Mile One', 'city' => 'St. John\'s IceCaps'],
//                    ['team' => 'Toronto Marlies', 'stadium' => 'Coca-Cola', 'city' => 'Toronto'],
//                    ['team' => 'Toronto Maple Leafs', 'stadium' => 'Scotiabank', 'city' => 'Toronto'],
//                    ['team' => 'Edmonton Oilers', 'stadium' => 'Rogers', 'city' => 'Edmonton'],
//                    ['team' => 'Granby Inouk', 'stadium' => 'Leonard-Grondin', 'city' => 'Granby'],
//                    ['team' => 'Drumheller Dragons', 'stadium' => 'Drumheller', 'city' => 'Drumheller'],
//                    ['team' => 'Kamloops Blazers', 'stadium' => 'Sandman', 'city' => 'Kamloops'],
//                    ['team' => 'Quebec Remparts', 'stadium' => 'Videotron', 'city' => 'Quebec'],
//                    ['team' => 'Kelowna Rockets', 'stadium' => 'Prospera', 'city' => 'Kelowna'],
//                    ['team' => 'Kootenay Ice', 'stadium' => 'Western Financial', 'city' => 'Cranbrook'],
//                    ['team' => 'Lethbridge Hurricanes', 'stadium' => 'ENMAX', 'city' => 'Lethbridge'],
//                    ['team' => 'Medicine Hat Tigers', 'stadium' => 'Canalta', 'city' => 'Medicine Hat'],
//                    ['team' => 'Prince George Cougars', 'stadium' => 'CN', 'city' => 'Prince George'],
//                    ['team' => 'Sudbury Wolves', 'stadium' => 'Sudbury', 'city' => 'Sudbury'],
//                    ['team' => 'Saskatoon Blades', 'stadium' => 'SaskTel', 'city' => 'Saskatoon'],
//                    ['team' => 'Sault Ste. Marie Greyhounds', 'stadium' => 'GFL', 'city' => 'Sault Ste. Marie'],
//                    ['team' => 'Fairview Flyers', 'stadium' => 'Fairview', 'city' => 'Fairview'],
//                    ['team' => 'Shelburne Sharks', 'stadium' => 'Dufferin', 'city' => 'Shelburne'],
//                    ['team' => 'Sherbrooke Phoenix', 'stadium' => 'Leopold-Drolet', 'city' => 'Sherbrooke'],
//                    ['team' => 'Edmonton Oil Kings', 'stadium' => 'Rogers', 'city' => 'Edmonton'],
//                    ['team' => 'Laval Saints', 'stadium' => 'Laval', 'city' => 'Laval'],
//                    ['team' => 'Terrebonne Cobras', 'stadium' => 'Terrebonne', 'city' => 'Terrebonne'],
//                ],
//            ],
//            [
//                'country' => 'USA',
//                'list' => [
//                    ['team' => 'Anaheim Ducks', 'stadium' => 'Honda', 'city' => 'Anaheim'],
//                    ['team' => 'Boston Bruins', 'stadium' => 'TD', 'city' => 'Boston'],
//                    ['team' => 'Washington Capitals', 'stadium' => 'Capital One', 'city' => 'Washington'],
//                    ['team' => 'Dallas Stars', 'stadium' => 'American Airlines', 'city' => 'Dallas'],
//                    ['team' => 'Detroit Red Wings', 'stadium' => 'Little Caesars', 'city' => 'Detroit'],
//                    ['team' => 'Los Angeles Kings', 'stadium' => 'Staples', 'city' => 'Los Angeles'],
//                    ['team' => 'New York Islanders', 'stadium' => 'Barclays', 'city' => 'New York'],
//                    ['team' => 'New York Rangers', 'stadium' => 'Madison Square', 'city' => 'New York'],
//                    ['team' => 'Nashville Predators', 'stadium' => 'Bridgestone', 'city' => 'Nashville'],
//                    ['team' => 'Pittsburgh Penguins', 'stadium' => 'PPG Paints', 'city' => 'Pittsburgh'],
//                    ['team' => 'San Jose Sharks', 'stadium' => 'SAP', 'city' => 'San Jose'],
//                    ['team' => 'St. Louis Blues', 'stadium' => 'Enterprise', 'city' => 'St. Louis'],
//                    ['team' => 'Tampa Bay Lightning', 'stadium' => 'Amalie', 'city' => 'Tampa'],
//                    ['team' => 'Philadelphia Flyers', 'stadium' => 'Wells Fargo', 'city' => 'Philadelphia'],
//                    ['team' => 'Florida Panthers', 'stadium' => 'BB&T', 'city' => 'Sunrise'],
//                    ['team' => 'Chicago Blackhawks', 'stadium' => 'United', 'city' => 'Chicago'],
//                    ['team' => 'Iowa Wild', 'stadium' => 'Wells Fargo', 'city' => 'Des Moines'],
//                    ['team' => 'Arizona Coyotes', 'stadium' => 'Gila River', 'city' => 'Glendale'],
//                    ['team' => 'Buffalo Sabres', 'stadium' => 'KeyBank', 'city' => 'Buffalo'],
//                    ['team' => 'Bakersfield Condors', 'stadium' => 'Rabobank', 'city' => 'Bakersfield'],
//                    ['team' => 'Grand Rapids Griffins', 'stadium' => 'Van Andel', 'city' => 'Grand Rapids'],
//                    ['team' => 'Carolina Hurricanes', 'stadium' => 'PNC', 'city' => 'Raleigh'],
//                    ['team' => 'Columbus Blue Jackets', 'stadium' => 'Nationwide', 'city' => 'Columbus'],
//                    ['team' => 'Colorado Avalanche', 'stadium' => 'Pepsi', 'city' => 'Denver'],
//                    ['team' => 'Cleveland Monsters', 'stadium' => 'Quicken Loans', 'city' => 'Quicken'],
//                    ['team' => 'Milwaukee Admirals', 'stadium' => 'UW–Milwaukee', 'city' => 'Milwaukee'],
//                    ['team' => 'Minnesota Wild', 'stadium' => 'Xcel Energy', 'city' => 'Saint Paul'],
//                    ['team' => 'New Jersey Devils', 'stadium' => 'Prudential', 'city' => 'Newark'],
//                    ['team' => 'Rockford IceHogs', 'stadium' => 'BMO Harris Bank', 'city' => 'Rockford'],
//                    ['team' => 'Stockton Heat', 'stadium' => 'Stockton', 'city' => 'Stockton'],
//                    ['team' => 'Texas Stars', 'stadium' => 'H-E-B', 'city' => 'Cedar Park'],
//                    ['team' => 'Chicago Wolves', 'stadium' => 'Allstate', 'city' => 'Rosemont'],
//                    ['team' => 'Syracuse Crunch', 'stadium' => 'Oncenter War Memorial', 'city' => 'Syracuse'],
//                    ['team' => 'Vegas Golden Knights', 'stadium' => 'Paradise', 'city' => 'T-Mobile'],
//                ],
//            ],
//            [
//                'country' => 'Russia',
//                'list' => [
//                    ['team' => 'Dynamo', 'city' => 'Moscow', 'stadium' => 'VTB'],
//                    ['team' => 'Severstal', 'city' => 'Cherepovets', 'stadium' => 'Ice Palace'],
//                    ['team' => 'SKA', 'city' => 'Saint Petersburg', 'stadium' => 'Saint Petersburg'],
//                    ['team' => 'Spartak', 'city' => 'Moscow', 'stadium' => 'Luzhniki'],
//                    ['team' => 'CSKA', 'city' => 'Moscow', 'stadium' => 'CSKA'],
//                    ['team' => 'Lokomotiv', 'city' => 'Yaroslavl', 'stadium' => '2000'],
//                    ['team' => 'Sochi', 'city' => 'Sochi', 'stadium' => 'Bolshoy'],
//                    ['team' => 'Vityaz', 'city' => 'Podolsk', 'stadium' => 'Vityaz'],
//                    ['team' => 'Ak Bars', 'city' => 'Kazan', 'stadium' => 'TatNeft'],
//                    ['team' => 'Avtomobilist', 'city' => 'Yekaterinburg', 'stadium' => 'Uralets'],
//                    ['team' => 'Metallurg', 'city' => 'Magnitogorsk', 'stadium' => 'Metallurg'],
//                    ['team' => 'Neftekhimik', 'city' => 'Nizhnekamsk', 'stadium' => 'SCC'],
//                    ['team' => 'Torpedo', 'city' => 'Nizhny Novgorod', 'stadium' => 'Trade Union'],
//                    ['team' => 'Traktor', 'city' => 'Chelyabinsk', 'stadium' => 'Traktor'],
//                    ['team' => 'Admiral', 'city' => 'Vladivostok', 'stadium' => 'Fetisov'],
//                    ['team' => 'Amur', 'city' => 'Khabarovsk', 'stadium' => 'Platinum'],
//                    ['team' => 'Avangard', 'city' => 'Omsk', 'stadium' => 'Omsk'],
//                    ['team' => 'Salavat Yulaev', 'city' => 'Ufa', 'stadium' => 'Ufa'],
//                    ['team' => 'Sibir', 'city' => 'Novosibirsk', 'stadium' => 'Sibir'],
//                    ['team' => 'Dinamo', 'city' => 'Saint Petersburg', 'stadium' => 'Yubileyny'],
//                    ['team' => 'SKA-Neva', 'city' => 'Saint Petersburg', 'stadium' => 'Yubileyny'],
//                    ['team' => 'Neftyanik', 'city' => 'Almetyevsk', 'stadium' => 'Yubileyny'],
//                    ['team' => 'Zauralie', 'city' => 'Kurgan', 'stadium' => 'Mostovik'],
//                    ['team' => 'Ermak', 'city' => 'Angarsk', 'stadium' => 'Ermak'],
//                    ['team' => 'Sokol', 'city' => 'Krasnoyarsk', 'stadium' => 'Sever'],
//                    ['team' => 'Sarov', 'city' => 'Sarov', 'stadium' => 'Sarov'],
//                    ['team' => 'Toros', 'city' => 'Neftekamsk', 'stadium' => 'Neftekamsk'],
//                    ['team' => 'Zvezda', 'city' => 'Chekhov', 'stadium' => 'Vityaz'],
//                    ['team' => 'Yuzhny Ural', 'city' => 'Orsk', 'stadium' => 'Yubileyny'],
//                    ['team' => 'Metallurg ', 'city' => 'Novokuznetsk', 'stadium' => 'Kuznetsk Metallurgists'],
//                    ['team' => 'Khimik', 'city' => 'Voskresensk', 'stadium' => 'Podmoskovie'],
//                    ['team' => 'Molot-Prikamye', 'city' => 'Perm', 'stadium' => 'Molot'],
//                    ['team' => 'Rubin', 'city' => 'Tyumen', 'stadium' => 'Tyumen'],
//                    ['team' => 'Dizel', 'city' => 'Penza', 'stadium' => 'Dizel'],
//                ],
//            ],
//            [
//                'country' => 'Finland',
//                'list' => [
//                    ['team' => 'HIFK', 'city' => 'Helsinki', 'stadium' => 'Helsinki'],
//                    ['team' => 'HPK', 'city' => 'Hameenlinna', 'stadium' => 'Patria'],
//                    ['team' => 'Ilves', 'city' => 'Tampere', 'stadium' => 'Tampere'],
//                    ['team' => 'Jukurit', 'city' => 'Mikkeli', 'stadium' => 'Ikioma'],
//                    ['team' => 'JYP', 'city' => 'Jyvaskyla', 'stadium' => 'Synergia'],
//                    ['team' => 'KalPa', 'city' => 'Kuopio', 'stadium' => 'Niiralan'],
//                    ['team' => 'KooKoo', 'city' => 'Kouvola', 'stadium' => 'Lumon'],
//                    ['team' => 'Karpat', 'city' => 'Oulu', 'stadium' => 'Oulun Energia'],
//                    ['team' => 'Lukko', 'city' => 'Rauma', 'stadium' => 'Kivikylan'],
//                    ['team' => 'Pelicans', 'city' => 'Lahti', 'stadium' => 'Isku'],
//                    ['team' => 'SaiPa', 'city' => 'Lappeenranta', 'stadium' => 'Kisapuisto'],
//                    ['team' => 'Vaasa Sport', 'city' => 'Vaasa', 'stadium' => 'Vaasa'],
//                    ['team' => 'Tappara', 'city' => 'Tampere', 'stadium' => 'Tampere'],
//                    ['team' => 'TPS', 'city' => 'Turku', 'stadium' => 'Gatorade'],
//                    ['team' => 'Assat', 'city' => 'Pori', 'stadium' => 'Pori'],
//                    ['team' => 'Espoo United', 'city' => 'Espoo', 'stadium' => 'Espoo Metro'],
//                    ['team' => 'Hermes', 'city' => 'Kokkola', 'stadium' => 'Kokkola'],
//                    ['team' => 'Peli-Karhut', 'city' => 'Iisalmi', 'stadium' => 'Kankaan'],
//                    ['team' => 'Jokipojat', 'city' => 'Joensuu', 'stadium' => 'Mehtimaki'],
//                    ['team' => 'Kiekko-Vantaa', 'city' => 'Vantaa', 'stadium' => 'Trio'],
//                    ['team' => 'KeuPa', 'city' => 'Keuruu', 'stadium' => 'Keuruu'],
//                    ['team' => 'LeKi', 'city' => 'Lempaala', 'stadium' => 'Masku'],
//                    ['team' => 'Peliitat', 'city' => 'Heinola', 'stadium' => 'Versowood'],
//                    ['team' => 'Kiekko', 'city' => 'Rovaniemi', 'stadium' => 'Lappi'],
//                    ['team' => 'SaPKo', 'city' => 'Savonlinna', 'stadium' => 'Winter Salon'],
//                    ['team' => 'TUTO', 'city' => 'Turku', 'stadium' => 'Marli'],
//                    ['team' => 'JYP-Akatemia', 'city' => 'Jyvaskyla', 'stadium' => 'Synergia'],
//                    ['team' => 'D-Kiekko', 'city' => 'Jyvaskyla', 'stadium' => 'Synergia'],
//                    ['team' => 'FPS', 'city' => 'Forssa', 'stadium' => 'Forssa'],
//                    ['team' => 'Jokerit', 'city' => 'Helsinki', 'stadium' => 'Hartwall'],
//                    ['team' => 'Kettera', 'city' => 'Imatra', 'stadium' => 'Imatra Spa'],
//                    ['team' => 'KOOVEE', 'city' => 'Tampere', 'stadium' => 'Hakametsa'],
//                    ['team' => 'IPK', 'city' => 'Iisalmi', 'stadium' => 'Iisalmi'],
//                    ['team' => 'Grankulla', 'city' => 'Kauniainen', 'stadium' => 'Kauniainen'],
//                ],
//            ],
//            [
//                'country' => 'Sweden',
//                'list' => [
//                    ['team' => 'AIK', 'city' => 'Stockholm', 'stadium' => 'Hovet'],
//                    ['team' => 'Brynas', 'city' => 'Gavle', 'stadium' => 'Gavlerinken'],
//                    ['team' => 'Vaxjo Lakers', 'city' => 'Vaxjo', 'stadium' => 'Vida'],
//                    ['team' => 'Vasteras', 'city' => 'Вестерос', 'stadium' => 'ABB'],
//                    ['team' => 'Linkopings', 'city' => 'Linkopings', 'stadium' => 'Saab'],
//                    ['team' => 'Lulea', 'city' => 'Lulea', 'stadium' => 'Coop Norrbotten'],
//                    ['team' => 'Malmo Redhawks', 'city' => 'Malmo', 'stadium' => 'Malmo'],
//                    ['team' => 'MODO', 'city' => 'Ornskoldsvik', 'stadium' => 'Fjallraven'],
//                    ['team' => 'Rogle', 'city' => 'Angelholm', 'stadium' => 'Lindab'],
//                    ['team' => 'Sodertalje', 'city' => 'Sodertalje', 'stadium' => 'AXA Sports'],
//                    ['team' => 'Timra', 'city' => 'Timra', 'stadium' => 'NHK'],
//                    ['team' => 'Färjestad', 'city' => 'Karlstad', 'stadium' => 'Lofbergs'],
//                    ['team' => 'Frolunda', 'city' => 'Gothenburg', 'stadium' => 'Scandinavium'],
//                    ['team' => 'HV71', 'city' => 'Jonkoping', 'stadium' => 'Kinnarps'],
//                    ['team' => 'Skelleftea', 'city' => 'Skelleftea', 'stadium' => 'Skelleftea Kraft'],
//                    ['team' => 'Djurgardens', 'city' => 'Stockholm', 'stadium' => 'Hovet'],
//                    ['team' => 'Almtuna', 'city' => 'Uppsala', 'stadium' => 'Metallatervinning'],
//                    ['team' => 'Karlskoga', 'city' => 'Karlskoga', 'stadium' => 'Nobel'],
//                    ['team' => 'Boras', 'city' => 'Boras', 'stadium' => 'Boras'],
//                    ['team' => 'Kalix', 'city' => 'Kalix', 'stadium' => 'Fururinken'],
//                    ['team' => 'Karlskrona', 'city' => 'Karlskrona', 'stadium' => 'Karlskrona'],
//                    ['team' => 'Kiruna', 'city' => 'Kiruna', 'stadium' => 'Lombia'],
//                    ['team' => 'Kovland', 'city' => 'Kovland', 'stadium' => 'Kovland'],
//                    ['team' => 'Leksand', 'city' => 'Leksand', 'stadium' => 'Tegera'],
//                    ['team' => 'Mora', 'city' => 'Mora', 'stadium' => 'Smidjegrav'],
//                    ['team' => 'Oskarshamn', 'city' => 'Oskarshamn', 'stadium' => 'Oskarshamn'],
//                    ['team' => 'Sundsvall', 'city' => 'Sundsvall', 'stadium' => 'Sundsvall'],
//                    ['team' => 'Tingsryd', 'city' => 'Tingsryd', 'stadium' => 'Nelson Garden'],
//                    ['team' => 'Orebro', 'city' => 'Orebro', 'stadium' => 'Behrn'],
//                    ['team' => 'Ornskoldsvik', 'city' => 'Ornskoldsvik', 'stadium' => 'Ornskoldsvik'],
//                    ['team' => 'Ostersunds', 'city' => 'Ostersunds', 'stadium' => 'Östersunds'],
//                    ['team' => 'Ljungby', 'city' => 'Ljungby', 'stadium' => 'Ljungby'],
//                    ['team' => 'Vannas', 'city' => 'Vannas', 'stadium' => 'Vannas'],
//                    ['team' => 'Solleftea', 'city' => 'Solleftea', 'stadium' => 'Niphallen'],
//                ],
//            ],
//            [
//                'country' => 'Czech Republic',
//                'list' => [
//                    [
//                        'team' => 'Бенатки-над-Йизероу',
//                        'city' => 'Бенатки-над-Йизероу',
//                        'stadium' => 'Бенатки-над-Йизероу'
//                    ],
//                    ['team' => 'Били Тигржи', 'city' => 'Либерец', 'stadium' => 'Типспорт'],
//                    ['team' => 'Верва Литвинов', 'city' => 'Литвинов', 'stadium' => 'Иван Глинка'],
//                    ['team' => 'Витковице Стил', 'city' => 'Острава', 'stadium' => 'Острава'],
//                    ['team' => 'Злин', 'city' => 'Злин', 'stadium' => 'Лудка Кайку'],
//                    ['team' => 'Итон Пардубице', 'city' => 'Пардубице', 'stadium' => 'Пардубице'],
//                    ['team' => 'Кладно', 'city' => 'Кладно', 'stadium' => 'Зимний стадион'],
//                    ['team' => 'Комета', 'city' => 'Брно', 'stadium' => 'Кайот'],
//                    ['team' => 'Маунтфилд', 'city' => 'Градец-Кралове', 'stadium' => 'Градец-Кралове'],
//                    ['team' => 'Млада Болеслав', 'city' => 'Млада-Болеслав', 'stadium' => 'СКА-Энерго'],
//                    ['team' => 'Оломоуц', 'city' => 'Оломоуц', 'stadium' => 'Оломоуц'],
//                    ['team' => 'Оцеларжи', 'city' => 'Тршинец', 'stadium' => 'Верк'],
//                    ['team' => 'Пльзень', 'city' => 'Пльзень', 'stadium' => 'Пльзень'],
//                    ['team' => 'Славия', 'city' => 'Прага', 'stadium' => 'O2'],
//                    ['team' => 'Спарта', 'city' => 'Прага', 'stadium' => 'Типспорт'],
//                    ['team' => 'Энергия', 'city' => 'Карловы Вары', 'stadium' => 'КВ'],
//                    ['team' => 'Бероунски Медведи', 'city' => 'Бероун', 'stadium' => 'Бероун'],
//                    ['team' => 'Врхлаби', 'city' => 'Врхлаби', 'stadium' => 'Врхлаби'],
//                    ['team' => 'ВСЕС', 'city' => 'Градец-Кралове', 'stadium' => 'Градец'],
//                    ['team' => 'Гавиржов Пантрез', 'city' => 'Гавиржов', 'stadium' => 'Гавиржов'],
//                    ['team' => 'Гавличкув-Брод', 'city' => 'Гавличкув-Брод', 'stadium' => 'Гавличкув-Брод'],
//                    ['team' => 'Дукла', 'city' => 'Йиглава', 'stadium' => 'Йиглава'],
//                    ['team' => 'Зноймы Орлы', 'city' => 'Зноймо', 'stadium' => 'Хостан'],
//                    ['team' => 'Кадань', 'city' => 'Кадань', 'stadium' => 'Кадань'],
//                    ['team' => 'Яромерж', 'city' => 'Яромерж', 'stadium' => 'Яромерж'],
//                    ['team' => 'Салис Шумперк', 'city' => 'Шумперк', 'stadium' => 'Шумперк'],
//                    ['team' => 'Слезань Опава', 'city' => 'Опава', 'stadium' => 'Опава'],
//                    ['team' => 'Табор', 'city' => 'Табор', 'stadium' => 'Табор'],
//                    ['team' => 'Устсти Львы', 'city' => 'Усти-над-Лабем', 'stadium' => 'Злотобрамен'],
//                    ['team' => 'Хомутов', 'city' => 'Хомутов', 'stadium' => 'Хомутов'],
//                    ['team' => 'Хорака Славия', 'city' => 'Тршебич', 'stadium' => 'Тршебич'],
//                    ['team' => 'Хрудим', 'city' => 'Хрудим', 'stadium' => 'Хрудим'],
//                    ['team' => 'Зубр Пршеров', 'city' => 'Пршеров', 'stadium' => 'Пршеров'],
//                    ['team' => 'Техника Брно', 'city' => 'Брно', 'stadium' => 'Брно'],
//                ],
//            ],
//            [
//                'country' => 'Switzerland',
//                'list' => [
//                    ['team' => 'Ajoie', 'city' => 'Porrentruy', 'stadium' => 'Porrentruy'],
//                    ['team' => 'Ambri-Piotta', 'city' => 'Ambri', 'stadium' => 'Valascia'],
//                    ['team' => 'Basel', 'city' => 'Basel', 'stadium' => 'Basel'],
//                    ['team' => 'Bern', 'city' => 'Bern', 'stadium' => 'PostFinance'],
//                    ['team' => 'Biel', 'city' => 'Biel', 'stadium' => 'Biel'],
//                    ['team' => 'Davos', 'city' => 'Davos', 'stadium' => 'Vaillant'],
//                    ['team' => 'Geneve-Servette', 'city' => 'Geneva', 'stadium' => 'Vernets'],
//                    ['team' => 'Kloten', 'city' => 'Kloten', 'stadium' => 'Swiss'],
//                    ['team' => 'La Chaux-de-Fonds', 'city' => 'La Chaux-de-Fonds', 'stadium' => 'Melezes'],
//                    ['team' => 'Star Lausanne', 'city' => 'Lausanne', 'stadium' => 'Odyssee'],
//                    ['team' => 'Lausanne', 'city' => 'Lausanne', 'stadium' => 'Malley'],
//                    ['team' => 'Lugano', 'city' => 'Lugano', 'stadium' => 'Corner'],
//                    ['team' => 'Rapperswil-Jona Lakers', 'city' => 'Rapperswil', 'stadium' => 'St.Galler'],
//                    ['team' => 'Fribourg Gotteron', 'city' => 'Fribourg', 'stadium' => 'BCF'],
//                    ['team' => 'Zug', 'city' => 'Zug', 'stadium' => 'Bossard'],
//                    ['team' => 'Lions', 'city' => 'Zurich', 'stadium' => 'Кюснахт'],
//                    ['team' => 'Arosa', 'city' => 'Arosa', 'stadium' => 'Arosa'],
//                    ['team' => 'Villars', 'city' => 'Villars-sur-Ollon', 'stadium' => 'Villars'],
//                    ['team' => 'Wolves', 'city' => 'Lausanne', 'stadium' => 'Pontaise'],
//                    ['team' => 'Chur', 'city' => 'Chur', 'stadium' => 'Chur'],
//                    ['team' => 'Langenthal', 'city' => 'Langenthal', 'stadium' => 'Schoren'],
//                    ['team' => 'Lyss', 'city' => 'Lyss', 'stadium' => 'Lyss'],
//                    ['team' => 'Olten', 'city' => 'Olten', 'stadium' => 'Olten'],
//                    ['team' => 'Red Ice', 'city' => 'Martigny', 'stadium' => 'Forum'],
//                    ['team' => 'St. Moritz', 'city' => 'St. Moritz', 'stadium' => 'St. Moritz'],
//                    ['team' => 'Sierre', 'city' => 'Sierre', 'stadium' => 'Sierre'],
//                    ['team' => 'Tigers', 'city' => 'Langnau im Emmental', 'stadium' => 'Ilfis'],
//                    ['team' => 'Thurgau', 'city' => 'Weinfelden', 'stadium' => 'Weinfelden'],
//                    ['team' => 'Visp', 'city' => 'Visp', 'stadium' => 'Visp'],
//                    ['team' => 'Forward Morges', 'city' => 'Morges', 'stadium' => 'Morges'],
//                    ['team' => 'Herisau', 'city' => 'Herisau', 'stadium' => 'Herisau'],
//                    ['team' => 'Young Sprinters ', 'city' => 'Neuchatel', 'stadium' => 'Littoral'],
//                    ['team' => 'Seewen', 'city' => 'Seewen', 'stadium' => 'Seewen'],
//                    ['team' => 'Lucerne', 'city' => 'Lucerne', 'stadium' => 'Lucerne'],
//                ],
//            ],
//            [
//                'country' => 'Slovakia',
//                'list' => [
//                    ['team' => '37 Piestany', 'city' => 'Piestany', 'stadium' => 'Piestany'],
//                    ['team' => '46 Bardejov', 'city' => 'Bardejov', 'stadium' => 'Bardejov'],
//                    ['team' => 'Banska Bystrica', 'city' => 'Banska Bystrica', 'stadium' => 'Banska Bystrica'],
//                    ['team' => 'Dukla', 'city' => 'Trencin', 'stadium' => 'Trencin'],
//                    ['team' => 'Dukla', 'city' => 'Senica', 'stadium' => 'Senica'],
//                    ['team' => 'Zilina', 'city' => 'Zilina', 'stadium' => 'Zilina'],
//                    ['team' => 'Zvolen', 'city' => 'Zvolen', 'stadium' => 'Zvolen'],
//                    ['team' => 'Kosice', 'city' => 'Kosice', 'stadium' => 'Steel'],
//                    ['team' => 'Liptovsky Mikulas', 'city' => 'Liptovsky Mikulas', 'stadium' => 'Liptovsky Mikulas'],
//                    ['team' => 'Martin', 'city' => 'Martin', 'stadium' => 'Martin'],
//                    ['team' => 'Nitra', 'city' => 'Nitra', 'stadium' => 'Nitra'],
//                    ['team' => 'Orange 20', 'city' => 'Piestany', 'stadium' => 'Piestany'],
//                    ['team' => 'Poprad', 'city' => 'Poprad', 'stadium' => 'Poprad'],
//                    ['team' => 'Slovan', 'city' => 'Bratislava', 'stadium' => 'Ondrej Nepela'],
//                    ['team' => 'Tatranski Vlci', 'city' => 'Spisska Nova Ves', 'stadium' => 'Spis'],
//                    ['team' => 'HK 36', 'city' => 'Skalica', 'stadium' => 'Skalica'],
//                    ['team' => '07 Detva', 'city' => 'Detva', 'stadium' => 'Detva'],
//                    ['team' => '07 Presov', 'city' => 'Presov', 'stadium' => 'Presov'],
//                    ['team' => '91 Senica', 'city' => 'Senica', 'stadium' => 'Senica'],
//                    ['team' => '95 Povazska Bystrica', 'city' => 'Povazska Bystrica', 'stadium' => 'Povazska Bystrica'],
//                    ['team' => 'Brezno', 'city' => 'Brezno', 'stadium' => 'Brezno'],
//                    ['team' => 'Humenne', 'city' => 'Humenne', 'stadium' => 'Humenne'],
//                    ['team' => 'Dolny Kubin', 'city' => 'Dolny Kubin', 'stadium' => 'Dolny Kubin'],
//                    ['team' => 'Dukla', 'city' => 'Michalovce', 'stadium' => 'Michalovce'],
//                    ['team' => 'Kezmarok', 'city' => 'Kezmarok', 'stadium' => 'Kezmarok'],
//                    ['team' => 'Presov Penguins', 'city' => 'Presov', 'stadium' => 'Presov'],
//                    ['team' => 'Prievidza', 'city' => 'Prievidza', 'stadium' => 'Prievidza'],
//                    ['team' => 'Ruzinov', 'city' => 'Bratislava', 'stadium' => 'Vladimir Dzurilla'],
//                    ['team' => 'Slovan', 'city' => 'Gelnica', 'stadium' => 'Gelnica'],
//                    ['team' => 'Topolcany', 'city' => 'Topolcany', 'stadium' => 'Topolcany'],
//                    ['team' => 'Trebisov', 'city' => 'Trebisov', 'stadium' => 'Trebisov'],
//                    ['team' => 'Trnava', 'city' => 'Trnava', 'stadium' => 'Trnava'],
//                    ['team' => 'Zlate Moravce', 'city' => 'Zlate Moravce', 'stadium' => 'Zlate Moravce'],
//                    ['team' => 'Puchov', 'city' => 'Puchov', 'stadium' => 'Puchov'],
//                ],
//            ],
//            [
//                'country' => 'Belarus',
//                'list' => [
//                    ['team' => 'Brest', 'city' => 'Brest', 'stadium' => 'Brest'],
//                    ['team' => 'Vitebsk', 'city' => 'Vitebsk', 'stadium' => 'Vitebsk'],
//                    ['team' => 'Gazpromneft', 'city' => 'Minsk', 'stadium' => 'Minsk'],
//                    ['team' => 'Gomel', 'city' => 'Gomel', 'stadium' => 'Gomel'],
//                    ['team' => 'Dinamo', 'city' => 'Minsk', 'stadium' => 'Minsk'],
//                    ['team' => 'Dinamo', 'city' => 'Molodechno', 'stadium' => 'Molodechno'],
//                    ['team' => 'Shinnik', 'city' => 'Bobruisk', 'stadium' => 'Bobruisk'],
//                    ['team' => 'Lida', 'city' => 'Lida', 'stadium' => 'Lida'],
//                    ['team' => 'Metallurg', 'city' => 'Zhlobin', 'stadium' => 'Metallurg'],
//                    ['team' => 'Mogilev', 'city' => 'Mogilev', 'stadium' => 'Mogilev'],
//                    ['team' => 'Neman', 'city' => 'Grodno', 'stadium' => 'Grodno'],
//                    ['team' => 'Tivali', 'city' => 'Minsk', 'stadium' => 'Yunost'],
//                    ['team' => 'Khimik-SKA', 'city' => 'Novopolotsk', 'stadium' => 'Polimir'],
//                    ['team' => 'Shakhtyor', 'city' => 'Salihorsk', 'stadium' => 'Salihorsk'],
//                    ['team' => 'Yunior', 'city' => 'Minsk', 'stadium' => 'Minsk'],
//                    ['team' => 'Yunost', 'city' => 'Minsk', 'stadium' => 'Minsk'],
//                    ['team' => 'Avangard', 'city' => 'Minsk', 'stadium' => 'Minsk'],
//                    ['team' => 'Amatar', 'city' => 'Minsk', 'stadium' => 'Minsk'],
//                    ['team' => 'Atlant', 'city' => 'Minsk', 'stadium' => 'Minsk'],
//                    ['team' => 'Drakony', 'city' => 'Minsk', 'stadium' => 'Minsk'],
//                    ['team' => 'Ledovyye lvy', 'city' => 'Minsk', 'stadium' => 'Minsk'],
//                    ['team' => 'Mikst', 'city' => 'Minsk', 'stadium' => 'Minsk'],
//                    ['team' => 'Mif', 'city' => 'Minsk', 'stadium' => 'Minsk'],
//                    ['team' => 'Molnii', 'city' => 'Minsk', 'stadium' => 'Minsk'],
//                    ['team' => 'Region', 'city' => 'Minsk', 'stadium' => 'Minsk'],
//                    ['team' => 'Rubezh', 'city' => 'Minsk', 'stadium' => 'Minsk'],
//                    ['team' => 'Rubon', 'city' => 'Minsk', 'stadium' => 'Minsk'],
//                    ['team' => 'Sokol', 'city' => 'Minsk', 'stadium' => 'Minsk'],
//                    ['team' => 'Stolitsa', 'city' => 'Minsk', 'stadium' => 'Minsk'],
//                    ['team' => 'Stoitel', 'city' => 'Minsk', 'stadium' => 'Minsk'],
//                    ['team' => 'Phoenix', 'city' => 'Minsk', 'stadium' => 'Minsk'],
//                    ['team' => 'Kharakter', 'city' => 'Minsk', 'stadium' => 'Minsk'],
//                    ['team' => 'Berkut', 'city' => 'Minsk', 'stadium' => 'Minsk'],
//                    ['team' => 'Bisony', 'city' => 'Minsk', 'stadium' => 'Minsk'],
//                ],
//            ],
//            [
//                'country' => 'Germany',
//                'list' => [
//                    ['team' => 'Adler Mannheim', 'city' => 'Mannheim', 'stadium' => 'SAP'],
//                    ['team' => 'Eisberen Berlin', 'city' => 'Berlin', 'stadium' => 'Mercedes-Benz'],
//                    ['team' => 'Augsburger Panther', 'city' => 'Augsburg', 'stadium' => 'Curt Frenzel'],
//                    ['team' => 'Bad Nauheim', 'city' => 'Bad Nauheim', 'stadium' => 'Bad Nauheim'],
//                    ['team' => 'Hamburg Freezers', 'city' => 'Hamburg', 'stadium' => 'Barclaycard'],
//                    ['team' => 'Hannover Scorpions', 'city' => 'Hanover', 'stadium' => 'Langenhagen'],
//                    ['team' => 'Grizzlys Wolfsburg', 'city' => 'Wolfsburg', 'stadium' => 'Volksbank BraWo'],
//                    ['team' => 'Dusseldorf', 'city' => 'Dusseldorf', 'stadium' => 'ISS Dome'],
//                    ['team' => 'Iserlohn Roosters', 'city' => 'Iserlohn', 'stadium' => 'Eissporthalle'],
//                    ['team' => 'Ingolstadt', 'city' => 'Ingolstadt', 'stadium' => 'Saturn'],
//                    ['team' => 'Kassel Huskies', 'city' => 'Kassel', 'stadium' => 'Kassel'],
//                    ['team' => 'Kolner Haie', 'city' => 'Cologne', 'stadium' => 'Lanxess'],
//                    ['team' => 'Krefeld Pinguine', 'city' => 'Krefeld', 'stadium' => 'Konig Palast'],
//                    ['team' => 'Thomas Sabo Ice Tigers', 'city' => 'Nuremberg', 'stadium' => 'Nuremberg'],
//                    ['team' => 'Red Bull', 'city' => 'Munich', 'stadium' => 'Olympia'],
//                    ['team' => 'Fischtown Pinguins', 'city' => 'Bremerhaven', 'stadium' => 'Bremerhaven'],
//                    ['team' => 'Bayreuth', 'city' => 'Bayreuth', 'stadium' => 'Bayreuth'],
//                    ['team' => 'Bietigheim-Bissingen', 'city' => 'Bietigheim-Bissingen', 'stadium' => 'EnergieVerbund'],
//                    ['team' => 'Dresden Devils', 'city' => 'Dresden', 'stadium' => 'Эненрджи Вербунд'],
//                    ['team' => 'Fuchse Duisburg', 'city' => 'Duisburg', 'stadium' => 'Scania'],
//                    ['team' => 'Kaufbeuren', 'city' => 'Kaufbeuren', 'stadium' => 'Sparkassen'],
//                    ['team' => 'Crimmitschau', 'city' => 'Crimmitschau', 'stadium' => 'Sahnpark'],
//                    ['team' => 'Lausitzer Fuchse', 'city' => 'Weisswasser', 'stadium' => 'Weisswasser'],
//                    ['team' => 'Ravensburg Towerstars', 'city' => 'Ravensburg', 'stadium' => 'Ravensburg'],
//                    ['team' => 'Rizersi', 'city' => 'Garmisch-Partenkirchen', 'stadium' => 'Olympia'],
//                    ['team' => 'Rote Teufel', 'city' => 'Bad Nauheim', 'stadium' => 'Bad Nauheim'],
//                    ['team' => 'Starbulls Rosenheim', 'city' => 'Rosenheim', 'stadium' => 'Kathrein'],
//                    ['team' => 'Freiburg', 'city' => 'Freiburg im Breisgau', 'stadium' => 'Franz-Siegel'],
//                    ['team' => 'Frankfurt Lions', 'city' => 'Frankfurt', 'stadium' => 'Frankfurt'],
//                    ['team' => 'Heilbronner Falken', 'city' => 'Heilbronn', 'stadium' => 'Kolbenschmidt'],
//                    ['team' => 'Schwenninger Wild Wings', 'city' => 'Villingen-Schwenningen', 'stadium' => 'Helios'],
//                    ['team' => 'Straubing Tigers', 'city' => 'Straubing', 'stadium' => 'Pulverturm'],
//                    ['team' => 'Hannover Indians', 'city' => 'Hannover', 'stadium' => 'Pferdeturm'],
//                    ['team' => 'Essen Mosquitoes', 'city' => 'Essen', 'stadium' => 'Essen'],
//                ],
//            ],
//            [
//                'country' => 'Norway',
//                'list' => [
//                    ['team' => 'Bergen', 'city' => 'Bergen', 'stadium' => 'Bergen'],
//                    ['team' => 'Valerenga', 'city' => 'Oslo', 'stadium' => 'Jordal Amfi'],
//                    ['team' => 'Gjovik', 'city' => 'Gjovik', 'stadium' => 'Gjovik'],
//                    ['team' => 'Comet', 'city' => 'Halden', 'stadium' => 'Halden'],
//                    ['team' => 'Kongsvinger Knights', 'city' => 'Kongsvinger', 'stadium' => 'Kongsvinger'],
//                    ['team' => 'Larenskog', 'city' => 'Larenskog', 'stadium' => 'Larenskog'],
//                    ['team' => 'Lillehammer', 'city' => 'Lillehammer', 'stadium' => 'Kristins'],
//                    ['team' => 'Manglerud Star', 'city' => 'Oslo', 'stadium' => 'Manglerud'],
//                    ['team' => 'Rosenborg', 'city' => 'Trondheim', 'stadium' => 'Leangen'],
//                    ['team' => 'Sparta Warriors', 'city' => 'Sarpsborg', 'stadium' => 'Sparta'],
//                    ['team' => 'Stavanger Oilers', 'city' => 'Stavanger', 'stadium' => 'DNB'],
//                    ['team' => 'Storhamar', 'city' => 'Hamar', 'stadium' => 'Hamar'],
//                    ['team' => 'Stjernen', 'city' => 'Fredrikstad', 'stadium' => 'Stjernen'],
//                    ['team' => 'Tansberg Vikings', 'city' => 'Tansberg', 'stadium' => 'Tansberg'],
//                    ['team' => 'Frisk Asker', 'city' => 'Asker', 'stadium' => 'Asker'],
//                    ['team' => 'Furuset', 'city' => 'Oslo', 'stadium' => 'Furuset'],
//                    ['team' => 'Gruner', 'city' => 'Oslo', 'stadium' => 'Gruner'],
//                    ['team' => 'Kristiansand', 'city' => 'Kristiansand', 'stadium' => 'Kristiansand'],
//                    ['team' => 'Lyderhorn', 'city' => 'Bergen', 'stadium' => 'Bergen'],
//                    ['team' => 'Fana', 'city' => 'Bergen', 'stadium' => 'Bergen'],
//                    ['team' => 'Moss', 'city' => 'Moss', 'stadium' => 'Moss'],
//                    ['team' => 'Narvik', 'city' => 'Narvik', 'stadium' => 'Nordkraft'],
//                    ['team' => 'Nidaros', 'city' => 'Trondheim', 'stadium' => 'Leangen'],
//                    ['team' => 'Prinsdalen Wheels', 'city' => 'Oslo', 'stadium' => 'Gruner'],
//                    ['team' => 'Ringerike Panthers', 'city' => 'Hanefoss', 'stadium' => 'Schjongshallen'],
//                    ['team' => 'Tansberg', 'city' => 'Tansberg', 'stadium' => 'Tansberg'],
//                    ['team' => 'Tromsa', 'city' => 'Tromsa', 'stadium' => 'Tromsa'],
//                    ['team' => 'Hasle-Laren', 'city' => 'Oslo', 'stadium' => 'Laren'],
//                    ['team' => 'Seagulls', 'city' => 'Haugesund', 'stadium' => 'Haugesund'],
//                    ['team' => 'Skedsmo', 'city' => 'Skedsmo', 'stadium' => 'Skedsmo'],
//                    ['team' => 'Ice Hawks', 'city' => 'Ski', 'stadium' => 'Ski'],
//                    ['team' => 'Jutul', 'city' => 'Berum', 'stadium' => 'Berum'],
//                    ['team' => 'River Rats', 'city' => 'Drammen', 'stadium' => 'Drammen'],
//                    ['team' => 'Jar', 'city' => 'Berum', 'stadium' => 'Berum'],
//                ],
//            ],
            [
                'country' => 'Ukraine',
                'list' => [
//                    ['team' => 'Bilyi Bars', 'city' => 'Bila Tserkva', 'stadium' => 'Bila Tserkva'],
//                    ['team' => 'Budivelnyk', 'city' => 'Kyiv', 'stadium' => 'Kyiv'],
//                    ['team' => 'Haidamaky', 'city' => 'Vinnytsia', 'stadium' => 'Ice club'],
//                    ['team' => 'Vityaz', 'city' => 'Kharkiv', 'stadium' => 'Saltov Ice'],
//                    ['team' => 'Generals', 'city' => 'Kyiv', 'stadium' => 'Kyiv'],
//                    ['team' => 'Dyname', 'city' => 'Kharkiv', 'stadium' => 'Saltov Ice'],
//                    ['team' => 'Donbass', 'city' => 'Donetsk', 'stadium' => 'Druzhba'],
//                    ['team' => 'Druzhba-78', 'city' => 'Kharkiv', 'stadium' => 'Kharkiv'],
//                    ['team' => 'Kompanion', 'city' => 'Kyiv', 'stadium' => 'ATEK'],
//                    ['team' => 'Kremenchuk', 'city' => 'Kremenchuk', 'stadium' => 'Iceberg'],
//                    ['team' => 'Kryvbass', 'city' => 'Kryvyi Rih', 'stadium' => 'Kryvyi Rih'],
//                    ['team' => 'Lviv', 'city' => 'Lviv', 'stadium' => 'Novoyavorivsk'],
//                    ['team' => 'Moloda Gvardiya', 'city' => 'Donetsk', 'stadium' => 'Druzhba'],
//                    ['team' => 'Patriot', 'city' => 'Vinnytsia', 'stadium' => 'Vinnytsia'],
//                    ['team' => 'Podil', 'city' => 'Kyiv', 'stadium' => 'ATEK'],
                    ['team' => 'Sokil', 'city' => 'Kyiv', 'stadium' => 'Terminal'],
                    ['team' => 'ATEK', 'city' => 'Kyiv', 'stadium' => 'ATEK'],
//                    ['team' => 'Vorony', 'city' => 'Sumy', 'stadium' => 'Sumy'],
//                    ['team' => 'Gladiator', 'city' => 'Lviv', 'stadium' => 'Medic'],
//                    ['team' => 'Dnipro', 'city' => 'Kherson', 'stadium' => 'Favoryt'],
//                    ['team' => 'Liubart', 'city' => 'Lutsk', 'stadium' => 'Lutsk'],
//                    ['team' => 'Kryzhynka', 'city' => 'Kyiv', 'stadium' => 'Kryzhynka'],
//                    ['team' => 'Odessa', 'city' => 'Odessa', 'stadium' => 'Umka'],
//                    ['team' => 'Olimpia', 'city' => 'Kalush', 'stadium' => 'Kalush'],
//                    ['team' => 'Polytechnic', 'city' => 'Kyiv', 'stadium' => 'Avanhard'],
//                    ['team' => 'Olimpia', 'city' => 'Kyiv', 'stadium' => 'Kyiv'],
//                    ['team' => 'Favoryt', 'city' => 'Rivne', 'stadium' => 'Rivne'],
//                    ['team' => 'Tsunami', 'city' => 'Ivano-Frankivsk', 'stadium' => 'Ivano-Frankivsk'],
//                    ['team' => 'Express', 'city' => 'Lviv', 'stadium' => 'Medic'],
//                    ['team' => 'Enei', 'city' => 'Drohobych', 'stadium' => 'Drohobych'],
//                    ['team' => 'Yunist', 'city' => 'Kharkiv', 'stadium' => 'Saltov Ice'],
//                    ['team' => 'Yavir', 'city' => 'Yavoriv', 'stadium' => 'Yavoriv'],
//                    ['team' => 'Vedmedi', 'city' => 'Uzhhorod', 'stadium' => 'Uzhhorod'],
//                    ['team' => 'Podolyany', 'city' => 'Ternopil', 'stadium' => 'Ternopil'],
                ],
            ],
        ];

        foreach ($team_array as $country) {
            $countryId = Country::find()
                ->select(['country_id'])
                ->where(['country_name' => $country['country']])
                ->limit(1)
                ->scalar();

            shuffle($country['list']);

            foreach ($country['list'] as $item) {
                $transaction = Yii::$app->db->beginTransaction();
                try {
                    $city = City::findOne(['city_name' => $item['city']]);
                    if (!$city) {
                        $city = new City();
                        $city->city_country_id = $countryId;
                        $city->city_name = $item['city'];
                        if (!$city->save()) {
                            throw new Exception(ErrorHelper::modelErrorsToString($city));
                        }
                    }

                    $stadium = new Stadium();
                    $stadium->stadium_city_id = $city->city_id;
                    $stadium->stadium_name = $item['stadium'];
                    if (!$stadium->save()) {
                        throw new Exception(ErrorHelper::modelErrorsToString($stadium));
                    }

                    $team = new Team();
                    $team->team_stadium_id = $stadium->stadium_id;
                    $team->team_name = $item['team'];
                    if (!$team->save()) {
                        throw new Exception(ErrorHelper::modelErrorsToString($team));
                    }

                    $transaction->commit();
                } catch (Exception $e) {
                    $transaction->rollBack();
                    ErrorHelper::log($e);
                }
            }
        }
    }
}
