<?php

include(__DIR__ . '/../include/include.php');

$exception_array = array(
    'folder' => array(
        '.git',
    ),
    'file' => array(
        '.gitignore',
        '.htaccess',
        'activation.php',
        'activation_repeat.php',
        'admin/city_create.php',
        'admin/city_delete.php',
        'admin/city_list.php',
        'admin/city_update.php',
        'admin/city_view.php',
        'admin/code_review.php',
        'admin/country_create.php',
        'admin/country_delete.php',
        'admin/country_list.php',
        'admin/country_update.php',
        'admin/country_view.php',
        'admin/debug_delete.php',
        'admin/debug_list.php',
        'admin/debug_truncate.php',
        'admin/index.php',
        'admin/name_create.php',
        'admin/name_delete.php',
        'admin/name_list.php',
        'admin/name_update.php',
        'admin/name_view.php',
        'admin/news_create.php',
        'admin/news_delete.php',
        'admin/news_list.php',
        'admin/news_update.php',
        'admin/news_view.php',
        'admin/rule_create.php',
        'admin/rule_delete.php',
        'admin/rule_list.php',
        'admin/rule_update.php',
        'admin/rule_view.php',
        'admin/schedule_change.php',
        'admin/site_version.php',
        'admin/stadium_create.php',
        'admin/stadium_delete.php',
        'admin/stadium_list.php',
        'admin/stadium_update.php',
        'admin/stadium_view.php',
        'admin/support_list.php',
        'admin/support_view.php',
        'admin/surname_create.php',
        'admin/surname_delete.php',
        'admin/surname_list.php',
        'admin/surname_update.php',
        'admin/surname_view.php',
        'admin/team_create.php',
        'admin/team_delete.php',
        'admin/team_list.php',
        'admin/team_update.php',
        'admin/team_view.php',
        'admin/teamask_delete.php',
        'admin/teamask_list.php',
        'admin/teamask_update.php',
        'admin/teamask_view.php',
        'admin/tournamenttype_create.php',
        'admin/tournamenttype_delete.php',
        'admin/tournamenttype_list.php',
        'admin/tournamenttype_update.php',
        'admin/tournamenttype_view.php',
        'admin/user_list.php',
        'admin/user_update.php',
        'admin/user_view.php',
        'admin/vote_create.php',
        'admin/vote_delete.php',
        'admin/vote_list.php',
        'admin/vote_ok.php',
        'admin/vote_update.php',
        'admin/vote_view.php',
        'admin/view/city_list.php',
        'admin/view/city_update.php',
        'admin/view/city_view.php',
        'admin/view/code_review.php',
        'admin/view/country_list.php',
        'admin/view/country_update.php',
        'admin/view/country_view.php',
        'admin/view/debug_list.php',
        'admin/view/index.php',
        'admin/view/include/breadcrumb.php',
        'admin/view/include/pagination.php',
        'admin/view/include/summary.php',
        'admin/view/layout/main.php',
        'admin/view/name_list.php',
        'admin/view/name_update.php',
        'admin/view/name_view.php',
        'admin/view/news_list.php',
        'admin/view/news_update.php',
        'admin/view/news_view.php',
        'admin/view/rule_list.php',
        'admin/view/rule_update.php',
        'admin/view/rule_view.php',
        'admin/view/schedule_change.php',
        'admin/view/site_version.php',
        'admin/view/stadium_list.php',
        'admin/view/stadium_update.php',
        'admin/view/stadium_view.php',
        'admin/view/support_list.php',
        'admin/view/support_view.php',
        'admin/view/surname_list.php',
        'admin/view/surname_update.php',
        'admin/view/surname_view.php',
        'admin/view/team_list.php',
        'admin/view/team_update.php',
        'admin/view/team_view.php',
        'admin/view/teamask_list.php',
        'admin/view/teamask_view.php',
        'admin/view/tournamenttype_list.php',
        'admin/view/tournamenttype_update.php',
        'admin/view/tournamenttype_view.php',
        'admin/view/user_list.php',
        'admin/view/user_update.php',
        'admin/view/user_view.php',
        'admin/view/vote_list.php',
        'admin/view/vote_update.php',
        'admin/view/vote_view.php',
        'include/breadcrumb.php',
        'include/constant.php',
        'include/database.php',
        'include/filter.php',
        'include/function.php',
        'include/generator.php',
        'include/include.php',
        'include/Mail.php',
        'include/menu.php',
        'include/pagination_count.php',
        'include/pagination_offset.php',
        'include/routing.php',
        'include/season.php',
        'include/seo.php',
        'include/session.php',
        'include/site.php',
        'include/start.php',
        'include/table_link.php',
        'team_view.php',
        'view/activation.php',
        'view/activation_repeat.php',
        'view/team_view.php',
    ),
);

$file_array = array();

$file_array = f_igosja_read_dir_to_array($file_array, __DIR__ . '/../', $exception_array);

$breadcrumb_array[] = 'Code review';

$summary_from   = 1;
$summary_to     = count($file_array);
$count_item     = $summary_to;

include(__DIR__ . '/view/layout/main.php');