<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'frontend-views-link-learn-more' => 'Learn More',
    'frontend-views-site-index-h1' => 'Online manager for true hockey fans!',
    'frontend-views-site-index-h2-birthday' => 'Birthdays',
    'frontend-views-site-index-h2-federation-news' => 'News of federations',
    'frontend-views-site-index-h2-how' => 'How to become a manager of a hockey team?',
    'frontend-views-site-index-h2-reviews' => 'Hockey Analytics',
    'frontend-views-site-index-h4-news' => 'Latest Game News',
    'frontend-views-site-index-how-ask' => 'You can ask your questions to experienced players on the {forum}. For all the problems and questions, you can write to {support}.',
    'frontend-views-site-index-how-li-1' => '{register}, receive a email with the registration confirmation code;',
    'frontend-views-site-index-how-li-2' => 'to activate your registration with the code received in the email, on {confirm}',
    'frontend-views-site-index-how-li-3' => 'enter the site under your login and password;',
    'frontend-views-site-index-how-li-4' => 'apply for a free team;',
    'frontend-views-site-index-how-li-5' => 'wait for the moderator to review your application and return the club to your disposal;',
    'frontend-views-site-index-how-li-6' => 'to familiarize with the most simple sections of rules (at will);',
    'frontend-views-site-index-how-li-7' => 'that\'s all - start the game! - gradually delving into the subtleties and details of the gameplay.',
    'frontend-views-site-index-legend-counter' => 'Counter',
    'frontend-views-site-index-legend-forum' => 'Forum',
    'frontend-views-site-index-legend-payments' => 'Payments',
    'frontend-views-site-index-link-confirm-page' => 'this page',
    'frontend-views-site-index-link-forum' => 'forum',
    'frontend-views-site-index-link-register' => 'register in the game',
    'frontend-views-site-index-link-sign-up' => 'Sign Up',
    'frontend-views-site-index-link-support' => 'technical support for the site',
    'frontend-views-site-index-text-birthday' => '<span class="strong">Today\'s birthday</span> is celebrated by managers:',
    'frontend-views-site-index-text-birthday-years-old' => 'is {years} years old!',
    'frontend-views-site-index-text-how' => 'In order to become a participant in the game, you need:',
    'frontend-views-site-index-text-reviews' => 'Journalists of the Virtual Hockey League regularly publish reviews of the tours:',
    'frontend-views-site-index-text-seo' => '<p class="text-justify">
            For sure, each of us wanted to feel like a coach or a manager of a real hockey club.
            A fascinating search for talented players, the gradual development of infrastructure,
            the choice of suitable tactics for the game, regular matches and, of course, wins,
            titles and new achievements! This is what awaits you in our virtual hockey world.
            Plunge into it and create a club of your dreams!
        </p>
        <h4>Everyone can play our hockey online manager!</h4>
        <p class="text-justify">
            Our project is open to all! To start playing, you just need to go through
            an elementary registration procedure or go under your profile in social networks.
            <strong>"Virtual Hockey League"</strong> is a functional hockey online manager in which
            you will get the opportunity to go through an exciting way of developing your team
            from the lower divisions to victories in national championships and world cups!
        </p>
        {sign-up}
        <h4>You do not need to download anything!</h4>
        <p class="text-justify">
            Please note that our hockey online manager is a browser game.
            Therefore, you do not need to download any client programs, spend time
            on their tedious installation and subsequent configuration.
            For the game you only need access to the Internet and a few minutes of free time.
            In this case, participation in tournaments is <strong>absolutely free</strong>.
        </p>
        <h4 class="center header">You will definitely become a champion!</h4>
        <p class="text-justify">
            We want to emphasize that you do not need to sit at your computer for success.
            To gradually develop your club, participate in transfers and play calendar matches,
            you just have to be able to visit our site at least several times a week.
        </p>
        <h4 class="center header">
            Exciting hockey matches and the first victories are already waiting for you!
        </h4>
        <p class="text-justify">
            Hockey online manager <strong>"Virtual Hockey League"</strong> is more than a regular game.
            This is a community of people who are united by passion and love for hockey.
            Here you can find interesting people, get new acquaintances
            and just have a great time in a relaxed and most comfortable atmosphere.
            Forward, it\'s time to take the coaching chair and manager\'s office!
        </p>',
    'frontend-views-transfer-index-h1' => '',
    'frontend-widgets-menu-change-team' => 'Change team',
    'frontend-widgets-menu-federation' => 'Federation',
    'frontend-widgets-menu-forum' => 'Forum',
    'frontend-widgets-menu-home' => 'Home',
    'frontend-widgets-menu-loan' => 'Loan',
    'frontend-widgets-menu-messenger' => 'Messenger',
    'frontend-widgets-menu-national-team' => 'National team',
    'frontend-widgets-menu-news' => 'News',
    'frontend-widgets-menu-password' => 'Forgot your password?',
    'frontend-widgets-menu-player' => 'Players',
    'frontend-widgets-menu-poll' => 'Polls',
    'frontend-widgets-menu-profile' => 'Profile',
    'frontend-widgets-menu-rating' => 'Ratings',
    'frontend-widgets-menu-roster' => 'Roster',
    'frontend-widgets-menu-rule' => 'Rules',
    'frontend-widgets-menu-schedule' => 'Schedule',
    'frontend-widgets-menu-sign-up' => 'Sign up',
    'frontend-widgets-menu-store' => 'Store',
    'frontend-widgets-menu-support' => 'Support',
    'frontend-widgets-menu-team' => 'Teams',
    'frontend-widgets-menu-tournament' => 'Tournaments',
    'frontend-widgets-menu-transfer' => 'Transfer',
    'frontend-widgets-menu-vip' => 'VIP club',
    '{n, ordinal} season' => 'VIP-клуб',
];
