<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'bell-complaint' => 'Complaints',
    'bell-logos' => 'Logos',
    'bell-poll' => 'Polls',
    'bell-support' => 'Support',
    'bell-team-request' => 'Team requests',
    'gear-disable' => 'Disable site',
    'gear-enable' => 'Enable site',
    'gear-logout' => 'Log out',
    'gear-version' => 'Site version',
    'link-analytic' => 'Analytics',
    'link-block-reason' => 'Reasons for blocking',
    'link-city' => 'Cities',
    'link-coach' => 'Coaches',
    'link-country' => 'Countries',
    'link-forum' => 'Forum',
    'link-forum-chapter' => 'Chapters',
    'link-forum-group' => 'Groups',
    'link-indicator' => 'Site indicators',
    'link-news' => 'News',
    'link-poll' => 'Polls',
    'link-pre-news' => 'Preliminary news',
    'link-president' => 'Presidents',
    'link-rules' => 'Rules',
    'link-schedule' => 'Schedule',
    'link-snapshot' => 'Snapshot',
    'link-stadium' => 'Stadiums',
    'link-team' => 'Teams',
    'link-tournament-type' => 'Tournament types',
    'link-user' => 'Users',
    'nav-admin' => 'Admin',
];
