<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'label-age' => 'Y',
    'label-assist' => 'A',
    'label-country' => 'Nat',
    'label-game' => 'GP',
    'label-game-row' => 'P/R',
    'label-physical' => 'Ph',
    'label-player' => 'Player',
    'label-player-price' => 'Price',
    'label-plus-minus' => 'P/M',
    'label-position' => 'Pos',
    'label-power-nominal' => 'P',
    'label-power-real' => 'RP',
    'label-score' => 'G',
    'label-special' => 'Spec',
    'label-style' => 'St',
    'label-tire' => 'T',
];
