<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'link-1' => 'on vacation',
    'link-2' => 'Invite friends',
    'link-3' => 'technical support',
    'text-1' => 'Leaving for a long time and without the Internet - do not forget to set the status {link}',
    'text-2' => '{link} to the League and get rewards',
    'text-3' => 'If you have questions - ask them to the {link} specialists of the League.',
    'text-4' => 'You can achieve high results without breaking the rules',
    'text-5' => 'Play fair - so interesting to win',
];
