<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'base' => 'Base',
    'division' => 'Division',
    'finance' => 'Finances',
    'letter-guest' => 'G',
    'letter-home' => 'H',
    'level' => 'level',
    'link-change-team' => 'Apply for a team',
    'link-edit' => 'Edit',
    'link-friendly' => 'Organize a friendly match',
    'link-physical' => 'Change in physical',
    'link-questionnaire' => 'Personal data',
    'link-school' => 'Preparing youth',
    'link-scout' => 'Studying players',
    'link-send' => 'Send',
    'link-sign-up' => 'Sign up',
    'link-training' => 'Training players',
    'manager' => 'Manager',
    'nickname' => 'Nickname',
    'stadium' => 'Stadium',
    'vice' => 'Vice',
];
