<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'h1' => 'Forgot password?',
    'submit' => 'Recover password',
    'text-1' => '<p>
            Here you can request to send <strong>a forgotten password to your mailbox</strong>,
            which you specified when registering.
        </p>
        <p>
            Enter your <strong>login</strong> or <strong>email</strong>:
        </p>',
    'text-2' => '<p>
            If during the registration you entered your email incorrectly or it does not work anymore,
            <br/>
            then email us at <span class="strong">' . Yii::$app->params['infoEmail'] . '</span>
            <br/>
            and we will try to find your account manually.
        </p>',
];
