<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'h1' => 'Sign up',
    'submit' => 'Start a career as a manager',
    'text-1' => '<p>
            Your <span class="strong">career as a coach-manager</span>
            in the Virtual Hockey League begins right here and now.<br/>
            In order for us to distinguish you from other players, come up with a
            <span class="strong">username</span> and <span class="strong">password</span>:
        </p>',
    'text-2' => '<p>
            Your activation code will be sent to your <span class="strong">e-mail</span>.
            Then you can request a password if you forget it:
        </p>',
    'text-3' => '<p>
            Starting a manager\'s career, you accept an agreement on using the site.
        </p>
        <p>
            Please note, we are not allowed to play simultaneously with multiple nicknames.
        </p>',
];
