<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'development-mode' => 'The site is in development mode.<br/>Some features of the site may not be available.',
    'javascript-warning' => 'JavaScript is disabled in your browser. We recommend that you enable JavaScript to work properly.',
    'link-log-in' => 'Log in',
    'link-log-out' => 'Log out',
    'logo-alt' => 'Virtual Hockey Online League',
    'page-generated' => 'Page is generated in {time} sec.,',
    'page-memory' => 'Memory usage - {memory}b',
    'page-queries' => '{count} queries.',
];
