<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'change-team' => 'Change team',
    'federation' => 'Federation',
    'forum' => 'Forum',
    'home' => 'Home',
    'loan' => 'Loan',
    'messenger' => 'Messenger',
    'national-team' => 'National team',
    'news' => 'News',
    'password' => 'Forgot your password?',
    'player' => 'Players',
    'poll' => 'Polls',
    'profile' => 'Profile',
    'rating' => 'Ratings',
    'roster' => 'Roster',
    'rule' => 'Rules',
    'schedule' => 'Schedule',
    'sign-up' => 'Sign up',
    'store' => 'Store',
    'support' => 'Support',
    'team' => 'Teams',
    'tournament' => 'Tournaments',
    'transfer' => 'Transfer',
    'vip' => 'VIP club',
];
