<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'h1' => 'account activation',
    'link-repeat' => 'I have not received a letter',
    'submit' => 'Activate account',
    'text' => '<p>
            <strong> Activate your account</strong> - it means to confirm
            that the mailbox specified during registration belongs to you and works.
            <br/>
            Only after that you will be able to fully use the functions of the site.
        </p>
        <p>
            To activate your account you need to enter the activation code
            which was sent to you by email.
        </p>',
];
