<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'frontend-views-link-learn-more' => 'Детальніше',
    'frontend-views-site-index-h1' => 'Онлайн-менеджер для справжніх любителів хокею!',
    'frontend-views-site-index-h2-birthday' => 'Дні народження',
    'frontend-views-site-index-h2-federation-news' => 'Новини федерацій',
    'frontend-views-site-index-h2-how' => 'Як стати менеджером хокейної команди?',
    'frontend-views-site-index-h2-reviews' => 'Хокейна аналітика',
    'frontend-views-site-index-h4-news' => 'Останні ігрові новини',
    'frontend-views-site-index-how-ask' => 'Свої запитання ви можете задати досвідченим гравцям на {forum}. Про всі проблеми і питання ви можете написати в {support}.',
    'frontend-views-site-index-how-li-1' => '{register}, отримати лист з кодом підтвердження реєстрації;',
    'frontend-views-site-index-how-li-2' => 'активувати свою реєстрацію за допомогою коду, отриманого в листі, на {confirm};',
    'frontend-views-site-index-how-li-3' => 'зайти на сайт під своїм логіном і паролем;',
    'frontend-views-site-index-how-li-4' => 'подати заявку на нову або вільну команду;',
    'frontend-views-site-index-how-li-5' => 'дочекатися, поки модератор розгляне вашу заявку і віддасть клуб в ваше розпорядження;',
    'frontend-views-site-index-how-li-6' => 'ознайомитися з найпростішими розділами правил (за бажанням);',
    'frontend-views-site-index-how-li-7' => 'і все - приступити до гри! - поступово вникаючи в тонкощі і деталі ігрового процесу.',
    'frontend-views-site-index-legend-counter' => 'Лічильник',
    'frontend-views-site-index-legend-forum' => 'Форум',
    'frontend-views-site-index-legend-payments' => 'Платежі',
    'frontend-views-site-index-link-confirm-page' => 'цій сторінці',
    'frontend-views-site-index-link-forum' => 'форумі',
    'frontend-views-site-index-link-register' => 'зареєструватися в грі',
    'frontend-views-site-index-link-sign-up' => 'Зареєструватися',
    'frontend-views-site-index-link-support' => 'техпідтримку сайту',
    'frontend-views-site-index-text-birthday' => '<span class="strong">Сьогодні день народження</span> святкують менеджери:',
    'frontend-views-site-index-text-birthday-years-old' => 'виповнюється {years, plural, one{# рік} few{# роки} many{# років} other{# років}}!',
    'frontend-views-site-index-text-how' => 'Для того, щоб стати учасником гри, вам потрібно:',
    'frontend-views-site-index-text-reviews' => 'Журналісти Віртуальної Хокейної Ліги регулярно публікують огляди відбулися турів:',
    'frontend-views-site-index-text-seo' => '<p class="text-justify">
            Напевно кожен з нас мріяв відчути себе тренером або менеджером справжнього хокейного клубу.
            Захоплюючий пошук талановитих гравців, поступовий розвиток інфраструктури,
            вибір відповідної тактики на гру, регулярні матчі і, звичайно ж, перемоги, титули і нові досягнення!
            Саме це чекає Вас в нашому світі віртуального хокею. Пориньте в нього і створіть клуб своєї мрії!
        </p>
        <h4>Грати в наш хокейний онлайн-менеджер може кожен!</h4>
        <p class="text-justify">
            Наш проект відкритий для всіх!
            Щоб почати грати, Вам достатньо просто пройти елементарну процедуру реєстрації.
            <strong>"Віртуальна Хокейна Ліга"</strong> – це функціональний хокейний онлайн-менеджер,
            в якому Ви отримаєте можливість пройти захоплюючий шлях розвитку своєї команди
            від нижчих дивізіонів до перемог в національних чемпіонатах і світових кубках!
        </p>
        {sign-up}
        <h4>Завантажувати нічого не треба!</h4>
        <p class="text-justify">
            Звертаємо увагу, що наш хокейний онлайн-менеджер є браузерною грою.
            Тому Вам не треба буде завантажувати будь-які клієнтські програми,
            витрачати час на їх тяжку установку і наступну настройку.
            Для гри Вам необхідний тільки доступ до інтернету і кілька хвилин вільного часу.
            При цьому участь в турнірах є <strong>абсолютно безкоштовною</strong>.
        </p>
        <h4 class="center header">Ви обов\'язково станете чемпіоном!</h4>
        <p class="text-justify">
            Хочемо підкреслити, що для досягнення успіху Вам не треба цілодобово сидіти за комп\'ютером.
            Щоб поступово розвивати свій клуб, брати участь в трансферах і грати календарні матчі,
            Вам достатньо мати можливість хоча б кілька разів на тиждень відвідувати наш сайт.
        </p>
        <h4 class="center header">Захоплюючі хокейні матчі і перші перемоги вже чекають на Вас!</h4>
        <p class="text-justify">
            Хокейний онлайн-менеджер <strong>"Віртуальна Хокейна Ліга"</strong> - це більше, ніж звичайна гра.
            Це спільнота людей, які об\'єднані пристрастю і любов\'ю до хокею.
            Тут Ви обов\'язково зможете знайти цікавих людей, заведете нові знайомства
            і просто відмінно проведетё час в невимушеній і максимально комфортній атмосфері.
            Вперед, прийшов час зайняти тренерське крісло і кабінет менеджера!
        </p>',
    'frontend-views-transfer-index-h1' => 'Список хокеїстів, виставлених на трансфер',
    'frontend-widgets-menu-change-team' => 'Змінити клуб',
    'frontend-widgets-menu-federation' => 'Федерація',
    'frontend-widgets-menu-forum' => 'Форум',
    'frontend-widgets-menu-home' => 'Головна',
    'frontend-widgets-menu-loan' => 'Оренда',
    'frontend-widgets-menu-messenger' => 'Спілкування',
    'frontend-widgets-menu-national-team' => 'Збірна',
    'frontend-widgets-menu-news' => 'Новини',
    'frontend-widgets-menu-password' => 'Забули пароль?',
    'frontend-widgets-menu-player' => 'Гравці',
    'frontend-widgets-menu-poll' => 'Опитування',
    'frontend-widgets-menu-profile' => 'Профіль',
    'frontend-widgets-menu-rating' => 'Рейтинги',
    'frontend-widgets-menu-roster' => 'Ростер',
    'frontend-widgets-menu-rule' => 'Правила',
    'frontend-widgets-menu-schedule' => 'Розклад',
    'frontend-widgets-menu-sign-up' => 'Реєстрація',
    'frontend-widgets-menu-store' => 'Магазин',
    'frontend-widgets-menu-support' => 'Техпідтримка',
    'frontend-widgets-menu-team' => 'Команды',
    'frontend-widgets-menu-tournament' => 'Турніри',
    'frontend-widgets-menu-transfer' => 'Трансфер',
    'frontend-widgets-menu-vip' => 'VIP-клуб',
    '{n, ordinal} season' => '',
];
