<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'bell-complaint' => 'Скарги',
    'bell-logos' => 'Логотипи',
    'bell-poll' => 'Опитування',
    'bell-support' => 'Тех. підтримка',
    'bell-team-request' => 'Заявки на команди',
    'gear-disable' => 'Вимкнути',
    'gear-enable' => 'Увімкнути',
    'gear-logout' => 'Вихід',
    'gear-version' => 'Версія сайту',
    'link-analytic' => 'Ігрова статистика',
    'link-block-reason' => 'Причини блокування',
    'link-city' => 'Міста',
    'link-coach' => 'Теренери збірних',
    'link-country' => 'Країни',
    'link-forum' => 'Форум',
    'link-forum-chapter' => 'Розділи',
    'link-forum-group' => 'Групи',
    'link-indicator' => 'Показники сайту',
    'link-news' => 'Новини',
    'link-poll' => 'Опитування',
    'link-pre-news' => 'Попередні новини',
    'link-president' => 'Президенти федерацій',
    'link-rules' => 'Правила',
    'link-schedule' => 'Розклад',
    'link-snapshot' => 'Статистичні дані',
    'link-stadium' => 'Стадіони',
    'link-team' => 'Команди',
    'link-tournament-type' => 'Типи турнірів',
    'link-user' => 'Користувачі',
    'nav-admin' => 'Адмін',
];
