<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'password-html' => 'Ви запросили відновлення пароля на сайті Віртуальної Хокейної Ліги.
        <br>
        Щоб відновити пароль перейдіть за посиланням {link}.',
    'password-text' => 'Ви запросили відновлення пароля на сайті Віртуальної Хокейної Ліги.
        Щоб відновити пароль перейдіть за посиланням {link}.',
    'signUp-html' => 'Ви успішно зареєстровані на сайті Віртуальної Хокейної Ліги під логіном <strong>{login}</strong>.
        <br/>
        Щоб завершити реєстрацію підтвердіть свій email за посиланням {link}
        або введіть код <strong>{code}</strong> на сторінці {page}',
    'signUp-text' => 'Ви успішно зареєстровані на сайті Віртуальної Хокейної Ліги під логіном {login}.
        Щоб завершити реєстрацію підтвердіть свій email за посиланням {link} або введіть код {code} на сторінці {page}',
];
