<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'h1' => 'Активація облікового запис',
    'link-repeat' => 'Мені не прийшов лист',
    'submit' => 'Активувати обліковий запис',
    'text' => '<p>
            <strong>Активувати свій обліковий запис</strong> - це означае підтвердити,
            що вказана при реєстрації поштова скринька належить вам і працює.<br/>
            Тільки після цього ви зможете повністю користуватися функціями сайту.
        </p>
        <p>
            Для активації облікового запису вам потрібно ввести код активації,
            який був відправлений вам на електронну пошту.
        </p>',
];
