<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'h1' => 'Забули пароль?',
    'submit' => 'Відновити пароль',
    'text-1' => '<p>
            Тут ви можете запросити надсилання <strong>загубленого пароля на свою поштову скриньку</strong>,
            котра була вказан вами при реєстрації.
        </p>
        <p>
            Вкажіть ваш <strong>логін</strong> або <strong>email</strong>:
        </p>',
    'text-2' => '<p>
            Якщо при реєстрації ви ввели свій email невірно або він вже не працює,
            <br/>
            напишіть нам лист на <span class="strong">' . Yii::$app->params['infoEmail'] . '</span>
            <br/>
            і ми спопробуємо знайти ваш обліковий запис вручную.
        </p>',
];
