<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'forum' => 'Останні теми на форумі федерації',
    'indicator' => 'Показники вашої команди',
    'price-base' => 'Вартість будівель',
    'price-total' => 'Загальна вартість',
    's16' => 'Сила 16 кращих (s16)',
    's21' => 'Сила 21 кращого (s21)',
    's27' => 'Сила 27 кращих (s27)',
    'vs' => 'Рейтинг сили команди (Vs)',
];
