<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'base' => 'База',
    'division' => 'Дивізіон',
    'finance' => 'Фінанси',
    'letter-guest' => 'Г',
    'letter-home' => 'Д',
    'level' => 'рівень',
    'link-change-team' => 'Подати заявку на отримання команди',
    'link-edit' => 'Ред.',
    'link-friendly' => 'Організувати товариський матч',
    'link-physical' => 'Зміна фізичної форми',
    'link-questionnaire' => 'Особисті дані',
    'link-school' => 'Підготовка молоді',
    'link-scout' => 'Вивчення хокеїстів',
    'link-send' => 'Відпр.',
    'link-sign-up' => 'Зареєструватися',
    'link-training' => 'Тренування хокеїстів',
    'manager' => 'Менеджер',
    'nickname' => 'Нік',
    'stadium' => 'Стадіон',
    'vice' => 'Заступник',
];
