<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'h1' => 'Реєстрація в грі',
    'submit' => 'Почати кар\'єру менеджера',
    'text-1' => '<p>
            Ваша <strong>кар\'єра тренера-менеджера</strong>
            в Віртуальній Хокейній Лізі починається прямо тут і зараз.<br/>
            Для того, щоб ми могли відрізнити вас від інших гравців, придумайте собі
            <Strong>логін</strong> та <strong>пароль</strong>:
        </p>',
    'text-2' => '<p>
            На <strong>ваш e-mail</strong> відправиться код активації облікового запису.
            Потім туди можна вислати пароль, якщо ви його забудете:
        </p>',
    'text-3' => '<p>
            Починаючи кар\'єру менеджера, ви приймаєте угоду про користування сайтом.
        </p>
        <p>
            Зверніть увагу, у нас заборонено грати одночасно під кількома ніками.
        </p>',
];
