<?php

$q = array();

$q[] = 'CREATE TABLE `teamrating`
        (
            `teamrating_id` SMALLINT(5) PRIMARY KEY AUTO_INCREMENT,
            `teamrating_capacity_country` SMALLINT(5) DEFAULT 0,
            `teamrating_capacity_division` TINYINT(2) DEFAULT 0,
            `teamrating_capacity_league` SMALLINT(5) DEFAULT 0,
            `teamrating_power_c_16_country` SMALLINT(5) DEFAULT 0,
            `teamrating_power_c_16_division` TINYINT(2) DEFAULT 0,
            `teamrating_power_c_16_league` SMALLINT(5) DEFAULT 0,
            `teamrating_power_c_21_country` SMALLINT(5) DEFAULT 0,
            `teamrating_power_c_21_division` TINYINT(2) DEFAULT 0,
            `teamrating_power_c_21_league` SMALLINT(5) DEFAULT 0,
            `teamrating_power_c_27_country` SMALLINT(5) DEFAULT 0,
            `teamrating_power_c_27_division` TINYINT(2) DEFAULT 0,
            `teamrating_power_c_27_league` SMALLINT(5) DEFAULT 0,
            `teamrating_power_s_16_country` SMALLINT(5) DEFAULT 0,
            `teamrating_power_s_16_division` TINYINT(2) DEFAULT 0,
            `teamrating_power_s_16_league` SMALLINT(5) DEFAULT 0,
            `teamrating_power_s_21_country` SMALLINT(5) DEFAULT 0,
            `teamrating_power_s_21_division` TINYINT(2) DEFAULT 0,
            `teamrating_power_s_21_league` SMALLINT(5) DEFAULT 0,
            `teamrating_power_s_27_country` SMALLINT(5) DEFAULT 0,
            `teamrating_power_s_27_division` TINYINT(2) DEFAULT 0,
            `teamrating_power_s_27_league` SMALLINT(5) DEFAULT 0,
            `teamrating_power_v_country` SMALLINT(5) DEFAULT 0,
            `teamrating_power_v_division` TINYINT(2) DEFAULT 0,
            `teamrating_power_v_league` SMALLINT(5) DEFAULT 0,
            `teamrating_power_vs_country` SMALLINT(5) DEFAULT 0,
            `teamrating_power_vs_division` TINYINT(2) DEFAULT 0,
            `teamrating_power_vs_league` SMALLINT(5) DEFAULT 0,
            `teamrating_price_base_country` SMALLINT(5) DEFAULT 0,
            `teamrating_price_base_division` TINYINT(2) DEFAULT 0,
            `teamrating_price_base_league` SMALLINT(5) DEFAULT 0,
            `teamrating_price_finance_country` SMALLINT(5) DEFAULT 0,
            `teamrating_price_finance_division` TINYINT(2) DEFAULT 0,
            `teamrating_price_finance_league` SMALLINT(5) DEFAULT 0,
            `teamrating_price_player_country` SMALLINT(5) DEFAULT 0,
            `teamrating_price_player_division` TINYINT(2) DEFAULT 0,
            `teamrating_price_player_league` SMALLINT(5) DEFAULT 0,
            `teamrating_price_stadium_country` SMALLINT(5) DEFAULT 0,
            `teamrating_price_stadium_division` TINYINT(2) DEFAULT 0,
            `teamrating_price_stadium_league` SMALLINT(5) DEFAULT 0,
            `teamrating_price_total_country` SMALLINT(5) DEFAULT 0,
            `teamrating_price_total_division` TINYINT(2) DEFAULT 0,
            `teamrating_price_total_league` SMALLINT(5) DEFAULT 0,
            `teamrating_salary_country` SMALLINT(5) DEFAULT 0,
            `teamrating_salary_division` TINYINT(2) DEFAULT 0,
            `teamrating_salary_league` SMALLINT(5) DEFAULT 0,
            `teamrating_team_id` SMALLINT(5) DEFAULT 0,
            `teamrating_visitor_country` SMALLINT(5) DEFAULT 0,
            `teamrating_visitor_division` TINYINT(2) DEFAULT 0,
            `teamrating_visitor_league` SMALLINT(5) DEFAULT 0
        );';