<?php

$q = array();

$q[] = 'CREATE TABLE `teamrating`
        (
            `teamrating_id` INT(5) PRIMARY KEY AUTO_INCREMENT,
            `teamrating_capacity_country` INT(5) DEFAULT 0,
            `teamrating_capacity_division` INT(2) DEFAULT 0,
            `teamrating_capacity_league` INT(5) DEFAULT 0,
            `teamrating_power_c_16_country` INT(5) DEFAULT 0,
            `teamrating_power_c_16_division` INT(2) DEFAULT 0,
            `teamrating_power_c_16_league` INT(5) DEFAULT 0,
            `teamrating_power_c_21_country` INT(5) DEFAULT 0,
            `teamrating_power_c_21_division` INT(2) DEFAULT 0,
            `teamrating_power_c_21_league` INT(5) DEFAULT 0,
            `teamrating_power_c_27_country` INT(5) DEFAULT 0,
            `teamrating_power_c_27_division` INT(2) DEFAULT 0,
            `teamrating_power_c_27_league` INT(5) DEFAULT 0,
            `teamrating_power_s_16_country` INT(5) DEFAULT 0,
            `teamrating_power_s_16_division` INT(2) DEFAULT 0,
            `teamrating_power_s_16_league` INT(5) DEFAULT 0,
            `teamrating_power_s_21_country` INT(5) DEFAULT 0,
            `teamrating_power_s_21_division` INT(2) DEFAULT 0,
            `teamrating_power_s_21_league` INT(5) DEFAULT 0,
            `teamrating_power_s_27_country` INT(5) DEFAULT 0,
            `teamrating_power_s_27_division` INT(2) DEFAULT 0,
            `teamrating_power_s_27_league` INT(5) DEFAULT 0,
            `teamrating_power_v_country` INT(5) DEFAULT 0,
            `teamrating_power_v_division` INT(2) DEFAULT 0,
            `teamrating_power_v_league` INT(5) DEFAULT 0,
            `teamrating_power_vs_country` INT(5) DEFAULT 0,
            `teamrating_power_vs_division` INT(2) DEFAULT 0,
            `teamrating_power_vs_league` INT(5) DEFAULT 0,
            `teamrating_price_base_country` INT(5) DEFAULT 0,
            `teamrating_price_base_division` INT(2) DEFAULT 0,
            `teamrating_price_base_league` INT(5) DEFAULT 0,
            `teamrating_price_finance_country` INT(5) DEFAULT 0,
            `teamrating_price_finance_division` INT(2) DEFAULT 0,
            `teamrating_price_finance_league` INT(5) DEFAULT 0,
            `teamrating_price_player_country` INT(5) DEFAULT 0,
            `teamrating_price_player_division` INT(2) DEFAULT 0,
            `teamrating_price_player_league` INT(5) DEFAULT 0,
            `teamrating_price_stadium_country` INT(5) DEFAULT 0,
            `teamrating_price_stadium_division` INT(2) DEFAULT 0,
            `teamrating_price_stadium_league` INT(5) DEFAULT 0,
            `teamrating_price_total_country` INT(5) DEFAULT 0,
            `teamrating_price_total_division` INT(2) DEFAULT 0,
            `teamrating_price_total_league` INT(5) DEFAULT 0,
            `teamrating_salary_country` INT(5) DEFAULT 0,
            `teamrating_salary_division` INT(2) DEFAULT 0,
            `teamrating_salary_league` INT(5) DEFAULT 0,
            `teamrating_team_id` INT(5) DEFAULT 0,
            `teamrating_visitor_country` INT(5) DEFAULT 0,
            `teamrating_visitor_division` INT(2) DEFAULT 0,
            `teamrating_visitor_league` INT(5) DEFAULT 0
        );';