<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'frontend-views-link-learn-more' => 'Подробнее',
    'frontend-views-site-index-h1' => 'Онлайн-менеджер для истинных любителей хоккея!',
    'frontend-views-site-index-h2-birthday' => 'Дни рождения',
    'frontend-views-site-index-h2-federation-news' => 'Новости федераций',
    'frontend-views-site-index-h2-how' => 'Как стать менеджером хоккейной команды?',
    'frontend-views-site-index-h2-reviews' => 'Хоккейная аналитика',
    'frontend-views-site-index-h4-news' => 'Последние игровые новости',
    'frontend-views-site-index-how-ask' => 'Свои вопросы вы можете задать опытным игрокам на {forum}. Обо всех проблемах и вопросах вы можете написать в {support}.',
    'frontend-views-site-index-how-li-1' => '{register}, получить письмо с кодом подтверждения регистрации;',
    'frontend-views-site-index-how-li-2' => 'активировать свою регистрацию с помощью кода, полученного в письме, на {confirm};',
    'frontend-views-site-index-how-li-3' => 'зайти на сайт под своим логином и паролем;',
    'frontend-views-site-index-how-li-4' => 'подать заявку на новую или свободную команду;',
    'frontend-views-site-index-how-li-5' => 'дождаться, пока модератор рассмотрит вашу заявку и отдаст клуб в ваше распоряжение;',
    'frontend-views-site-index-how-li-6' => 'ознакомиться с самыми простыми разделами правил (по желанию);',
    'frontend-views-site-index-how-li-7' => 'и всё - приступить к игре! - постепенно вникая в тонкости и детали игрового процесса.',
    'frontend-views-site-index-legend-counter' => 'Счётчик',
    'frontend-views-site-index-legend-forum' => 'Форум',
    'frontend-views-site-index-legend-payments' => 'Платежи',
    'frontend-views-site-index-link-confirm-page' => 'этой странице',
    'frontend-views-site-index-link-forum' => 'форуме',
    'frontend-views-site-index-link-register' => 'зарегистрироваться в игре',
    'frontend-views-site-index-link-sign-up' => 'Зарегистрироваться',
    'frontend-views-site-index-link-support' => 'техподдержку сайта',
    'frontend-views-site-index-text-birthday' => '<span class="strong">Сегодня день рождения</span> празднуют менеджеры:',
    'frontend-views-site-index-text-birthday-years-old' => 'исполняется {years, plural, one{# год} few{# года} many{# лет} other{# лет}}!',
    'frontend-views-site-index-text-how' => 'Для того, чтобы стать участником игры, вам нужно:',
    'frontend-views-site-index-text-reviews' => 'Журналисты Виртуальной Хоккейной Лиги регулярно публикуют обзоры состоявшихся туров:',
    'frontend-views-site-index-text-seo' => '<p class="text-justify">
            Наверняка каждый из нас мечтал почувствовать себя тренером или менеджером настоящего хоккейного клуба.
            Увлекательный поиск талантливых игроков, постепенное развитие инфраструктуры,
            выбор подходящей тактики на игру, регулярные матчи и, конечно же, победы, титулы и новые достижения!
            Именно это ждёт Вас в нашем мире виртуального хоккея. Окунитесь в него и создайте клуб своей мечты!
        </p>
        <h4>Играть в наш хоккейный онлайн-менеджер может каждый!</h4>
        <p class="text-justify">
            Наш проект открыт для всех!
            Чтобы начать играть, Вам достаточно просто пройти элементарную процедуру регистрации.
            <strong>"Виртуальная Хоккейная Лига"</strong> – это функциональный хоккейный онлайн-менеджер,
            в котором Вы получите возможность пройти увлекательный путь развития своей команды
            от низших дивизионов до побед в национальных чемпионатах и мировых кубках!
        </p>
        {sign-up}
        <h4>Скачивать ничего не надо!</h4>
        <p class="text-justify">
            Обращаем внимание, что наш хоккейный онлайн-менеджер является браузерной игрой.
            Поэтому Вам не надо будет скачивать какие-либо клиентские программы,
            тратить время на их утомительную установку и последующую настройку.
            Для игры Вам необходим только доступ к интернету и несколько минут свободного времени.
            При этом участие в турнирах является <strong>абсолютно бесплатным</strong>.
        </p>
        <h4 class="center header">Вы обязательно станете чемпионом!</h4>
        <p class="text-justify">
            Хотим подчеркнуть, что для достижения успеха Вам не надо целыми сутками сидеть за компьютером.
            Чтобы постепенно развивать свой клуб, участвовать в трансферах и играть календарные матчи,
            Вам достаточно иметь возможность хотя бы несколько раз в неделю посещать наш сайт.
        </p>
        <h4 class="center header">Увлекательные хоккейные матчи и первые победы уже ждут Вас!</h4>
        <p class="text-justify">
            Хоккейный онлайн-менеджер <strong>"Виртуальная Хоккейная Лига"</strong> – это больше, чем обычная игра.
            Это сообщество людей, которые объединены страстью и любовью к хоккею.
            Здесь Вы обязательно сможете найти интересных людей, заведете новые знакомства
            и просто отлично проведетё время в непринужденной и максимально комфортной атмосфере.
            Вперёд, пришло время занять тренерское кресло и кабинет менеджера!
        </p>',
    'frontend-views-transfer-index-h1' => 'Список хоккеистов, выставленных на трансфер',
    'frontend-widgets-menu-change-team' => 'Сменить клуб',
    'frontend-widgets-menu-federation' => 'Федерация',
    'frontend-widgets-menu-forum' => 'Форум',
    'frontend-widgets-menu-home' => 'Главная',
    'frontend-widgets-menu-loan' => 'Аренда',
    'frontend-widgets-menu-messenger' => 'Общение',
    'frontend-widgets-menu-national-team' => 'Сборная',
    'frontend-widgets-menu-news' => 'Новости',
    'frontend-widgets-menu-password' => 'Забыли пароль?',
    'frontend-widgets-menu-player' => 'Игроки',
    'frontend-widgets-menu-poll' => 'Опросы',
    'frontend-widgets-menu-profile' => 'Профиль',
    'frontend-widgets-menu-rating' => 'Рейтинги',
    'frontend-widgets-menu-roster' => 'Ростер',
    'frontend-widgets-menu-rule' => 'Правила',
    'frontend-widgets-menu-schedule' => 'Расписание',
    'frontend-widgets-menu-sign-up' => 'Регистрация',
    'frontend-widgets-menu-store' => 'Магазин',
    'frontend-widgets-menu-support' => 'Техподдержка',
    'frontend-widgets-menu-team' => 'Команды',
    'frontend-widgets-menu-tournament' => 'Турниры',
    'frontend-widgets-menu-transfer' => 'Трансфер',
    'frontend-widgets-menu-vip' => '',
    '{n, ordinal} season' => '',
];
