<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'bell-complaint' => 'Жалобы',
    'bell-logos' => 'Логотипы',
    'bell-poll' => 'Опросы',
    'bell-support' => 'Тех. поддержка',
    'bell-team-request' => 'Заявки на команды',
    'gear-disable' => 'Выключить',
    'gear-enable' => 'Включить',
    'gear-logout' => 'Выход',
    'gear-version' => 'Версия сайта',
    'link-analytic' => 'Игровая статистика',
    'link-block-reason' => 'Причины блокировки',
    'link-city' => 'Города',
    'link-coach' => 'Теренеры сборных',
    'link-country' => 'Страны',
    'link-forum' => 'Форум',
    'link-forum-chapter' => 'Разделы',
    'link-forum-group' => 'Группы',
    'link-indicator' => 'Показатели сайта',
    'link-news' => 'Новости',
    'link-poll' => 'Опросы',
    'link-pre-news' => 'Предварительные новости',
    'link-president' => 'Президенты федераций',
    'link-rules' => 'Правила',
    'link-schedule' => 'Расписание',
    'link-snapshot' => 'Статистические данные',
    'link-stadium' => 'Стадионы',
    'link-team' => 'Команды',
    'link-tournament-type' => 'Типы турниров',
    'link-user' => 'Пользователи',
    'nav-admin' => 'Админ',
];
