<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'label-age' => 'В',
    'label-assist' => 'П',
    'label-country' => 'Нац',
    'label-game' => 'И',
    'label-game-row' => 'И/О',
    'label-physical' => 'Ф',
    'label-player' => 'Игрок',
    'label-player-price' => 'Цена',
    'label-plus-minus' => '+/-',
    'label-position' => 'Поз',
    'label-power-nominal' => 'С',
    'label-power-real' => 'РС',
    'label-score' => 'Г',
    'label-special' => 'Спец',
    'label-style' => 'Ст',
    'label-tire' => 'У',
];
