<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'link-1' => 'в отпуске',
    'link-2' => 'Пригласите друзей',
    'link-3' => 'тех.поддержки',
    'text-1' => 'Уезжая надолго и без интернета - не забудьте поставить статус {link}',
    'text-2' => '{link} в Лигу и получите вознаграждение',
    'text-3' => 'Если у вас есть вопросы - задайте их специалистам {link} Лиги',
    'text-4' => 'Можно достичь высоких результатов, не нарушая правил',
    'text-5' => 'Играйте честно - так интереснее выигрывать',
];
