<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'h1' => 'Регистрация в игре',
    'submit' => 'Начать карьеру менеджера',
    'text-1' => '<p>
            Ваша <strong>карьера тренера-менеджера</strong>
            в Виртуальной Хоккейной Лиге начинается прямо здесь и сейчас.<br/>
            Для того, чтобы мы могли отличить вас от других игроков, придумайте себе
            <strong>логин</strong> и <strong>пароль</strong>:
        </p>',
    'text-2' => '<p>
            На <strong>ваш e-mail</strong> отправится код активации аккаунта.
            Потом туда можно запросить пароль, если вы его забудете:
        </p>',
    'text-3' => '<p>
            Начиная карьеру менеджера, вы принимаете соглашение о пользовании сайтом.
        </p>
        <p>
            Обратите внимание, у нас запрещено играть одновременно под несколькими никами.
        </p>',
];
