<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'h1' => 'Активация аккаунта',
    'link-repeat' => 'Мне не пришло письмо',
    'submit' => 'Активировать аккаунт',
    'text' => '<p>
            <strong>Активировать свой аккаунт</strong> - это значит подтвердить,
            что указанный при регистрации почтовый ящик принадлежит вам и работает.<br/>
            Только после этого вы сможете полностью пользоваться функциями сайта.
        </p>
        <p>
            Для активации своего аккаунта вам нужно ввести код активации,
            который был отправлен вам по электронной почте.
        </p>',
];
