<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'change-team' => 'Сменить клуб',
    'federation' => 'Федерация',
    'forum' => 'Форум',
    'home' => 'Главная',
    'loan' => 'Аренда',
    'messenger' => 'Общение',
    'national-team' => 'Сборная',
    'news' => 'Новости',
    'password' => 'Забыли пароль?',
    'player' => 'Игроки',
    'poll' => 'Опросы',
    'profile' => 'Профиль',
    'rating' => 'Рейтинги',
    'roster' => 'Ростер',
    'rule' => 'Правила',
    'schedule' => 'Расписание',
    'sign-up' => 'Регистрация',
    'store' => 'Магазин',
    'support' => 'Техподдержка',
    'team' => 'Команды',
    'tournament' => 'Турниры',
    'transfer' => 'Трансфер',
    'vip' => 'VIP-клуб',
];
