<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'base' => '@@База@@',
    'division' => 'Дивизион',
    'finance' => 'Финансы',
    'letter-guest' => 'Г',
    'letter-home' => 'Д',
    'level' => 'уровень',
    'link-change-team' => 'Подать заявку на получение команды',
    'link-edit' => 'Ред.',
    'link-friendly' => 'Организовать товарищеский матч',
    'link-physical' => 'Изменение физической формы',
    'link-questionnaire' => 'Личные данные',
    'link-school' => 'Подготовка молодёжи',
    'link-scout' => 'Изучение хоккеистов',
    'link-send' => 'Отпр.',
    'link-sign-up' => 'Зарегистрироваться',
    'link-training' => 'Тренировка хоккеистов',
    'manager' => 'Менеджер',
    'nickname' => 'Ник',
    'stadium' => '@@Стадион@@',
    'vice' => 'Заместитель',
];
