<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'h1' => 'Забыли пароль?',
    'submit' => 'Восстановить пароль',
    'text-1' => '<p>
            Здесь вы можете запросить отправку <strong>забытого пароля на свой почтовый ящик</strong>,
            который был указан вами при регистрации.
        </p>
        <p>
            Укажите ваш <strong>логин</strong> или <strong>email</strong>:
        </p>',
    'text-2' => '<p>
            Если при регистрации вы ввели свой email неправильно или он уже не работает,
            <br/>
            то напишите нам письмо на <span class="strong">' . Yii::$app->params['infoEmail'] . '</span>
            <br/>
            и мы попробуем найти ваш аккаунт вручную.
        </p>',
];
